-- ATOMS v1.0.0 — GENERATED by TrialBox criteria-compiler from Criterion IR (SPEC §6.3).
-- Deterministic template output; never edited by hand or produced by an LLM.
-- Parameters: $1 index_dates DATE[] ; $2 pids VARCHAR[] (NULL = all patients alive at index).
-- Output: one row per (pid, index_date) with "C_<ID>" BOOLEAN/NULL and "E_<ID>" VARCHAR per criterion.
WITH
params AS (SELECT CAST($1 AS DATE[]) AS idx_dates, CAST($2 AS VARCHAR[]) AS pids),
idx AS (SELECT unnest(idx_dates) AS index_date FROM params),
base AS (
  SELECT p.pid, p.birth_date, p.sex, i.index_date FROM patient p CROSS JOIN idx i
  WHERE ((SELECT pids FROM params) IS NULL OR list_contains((SELECT pids FROM params), p.pid))
    AND (p.deceased_date IS NULL OR p.deceased_date > i.index_date)
    AND (p.birth_date IS NULL OR p.birth_date <= i.index_date)),
vs(vs_id, system, code) AS (VALUES
  ('VS_BARIATRIC_SURGERY', 'https://trialbox.local/fhir/CodeSystem/nhi-order', '75613B'),
  ('VS_BARIATRIC_SURGERY', 'https://trialbox.local/fhir/CodeSystem/nhi-order', '75614B'),
  ('VS_CHEST_X_RAY', 'http://loinc.org', '36643-5'),
  ('VS_COLCHICINE', 'http://www.whocc.no/atc', 'M04AC01'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.00'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.071'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.072'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.9'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.00X0'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.9XX0'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.9XX1'),
  ('VS_HBA1C', 'http://loinc.org', '4548-4'),
  ('VS_HBSAG', 'http://loinc.org', '5196-1'),
  ('VS_IGRA', 'http://loinc.org', '71774-4'),
  ('VS_METHOTREXATE', 'http://www.whocc.no/atc', 'L04AX03'),
  ('VS_RA_BIOLOGIC', 'https://trialbox.local/fhir/CodeSystem/nhi-drug', 'KC00017248'),
  ('VS_RA_BIOLOGIC', 'https://trialbox.local/fhir/CodeSystem/nhi-drug', 'KC00018248'),
  ('VS_RA_BIOLOGIC', 'https://trialbox.local/fhir/CodeSystem/nhi-drug', 'KC00019248'),
  ('VS_RHEUMATOLOGY_CLINIC_VISIT', 'https://trialbox.local/fhir/CodeSystem/department', 'RHEU'),
  ('VS_SERUM_URATE', 'http://loinc.org', '3084-1'),
  ('VS_SYSTOLIC_BLOOD_PRESSURE', 'http://loinc.org', '8480-6'),
  ('VS_TB_PREVENTIVE_THERAPY', 'http://www.whocc.no/atc', 'J04AB05'),
  ('VS_TB_PREVENTIVE_THERAPY', 'http://www.whocc.no/atc', 'J04AC01'),
  ('VS_TYPE_1_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E10.10'),
  ('VS_TYPE_1_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E10.65'),
  ('VS_TYPE_1_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E10.9')),
-- ATOMS-INC-01 (inclusion): age 18-75
c_atoms_inc_01 AS (
  SELECT b.pid, b.index_date, ((date_sub('year', b.birth_date, b.index_date) >= 18) AND (date_sub('year', b.birth_date, b.index_date) <= 75)) AS v,
         concat_ws(';', NULL) AS ev
  FROM base b
  ),
-- ATOMS-INC-02 (inclusion): female
c_atoms_inc_02 AS (
  SELECT b.pid, b.index_date, ((CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END)) AS v,
         concat_ws(';', NULL) AS ev
  FROM base b
  ),
a_atoms_inc_03_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GOUT' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-03 (inclusion): gout ever
c_atoms_inc_03 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_03_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_inc_03_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_03_1 ON a_atoms_inc_03_1.pid = b.pid AND a_atoms_inc_03_1.index_date = b.index_date),
a_atoms_inc_04_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GOUT' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -30) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-04 (inclusion): no gout dx in 30d
c_atoms_inc_04 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_04_1.n, 0) = 0) AS v,
         concat_ws(';', a_atoms_inc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_04_1 ON a_atoms_inc_04_1.pid = b.pid AND a_atoms_inc_04_1.index_date = b.index_date),
a_atoms_inc_05_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GOUT' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -730) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-05 (inclusion): >=2 gout dx in 2y
c_atoms_inc_05 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_05_1.n, 0) >= 2) AS v,
         concat_ws(';', a_atoms_inc_05_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_05_1 ON a_atoms_inc_05_1.pid = b.pid AND a_atoms_inc_05_1.index_date = b.index_date),
a_atoms_inc_06_1 AS (
  SELECT pid, index_date, coalesce(bool_or((o.value_num >= 8)), FALSE) AS v,
         string_agg(CASE WHEN (o.value_num >= 8) THEN o.oid || '|' || strftime(o.effective, '%Y-%m-%d') END, ';' ORDER BY o.effective, o.oid) AS ev
  FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code)) o GROUP BY pid, index_date),
-- ATOMS-INC-06 (inclusion): any urate >= 8 in 1y
c_atoms_inc_06 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_06_1.v AS v,
         concat_ws(';', a_atoms_inc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_06_1 ON a_atoms_inc_06_1.pid = b.pid AND a_atoms_inc_06_1.index_date = b.index_date),
a_atoms_inc_07_1 AS (
  SELECT pid, index_date, coalesce(bool_and((o.value_num < 9)), TRUE) AS v,
         string_agg(CASE WHEN (o.value_num < 9) THEN o.oid || '|' || strftime(o.effective, '%Y-%m-%d') END, ';' ORDER BY o.effective, o.oid) AS ev
  FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -730) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code)) o GROUP BY pid, index_date),
-- ATOMS-INC-07 (inclusion): all urate < 9 in 2y
c_atoms_inc_07 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_07_1.v AS v,
         concat_ws(';', a_atoms_inc_07_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_07_1 ON a_atoms_inc_07_1.pid = b.pid AND a_atoms_inc_07_1.index_date = b.index_date),
a_atoms_inc_08_1 AS (
  SELECT pid, index_date, NOT coalesce(bool_or((o.value_num > 10)), FALSE) AS v,
         string_agg(CASE WHEN (o.value_num > 10) THEN o.oid || '|' || strftime(o.effective, '%Y-%m-%d') END, ';' ORDER BY o.effective, o.oid) AS ev
  FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -730) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code)) o GROUP BY pid, index_date),
-- ATOMS-INC-08 (inclusion): no urate > 10 in 2y
c_atoms_inc_08 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_08_1.v AS v,
         concat_ws(';', a_atoms_inc_08_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_08_1 ON a_atoms_inc_08_1.pid = b.pid AND a_atoms_inc_08_1.index_date = b.index_date),
a_atoms_inc_09_1 AS (
  SELECT pid, index_date, (count(*) FILTER (WHERE (o.value_num >= 6)) >= 2) AS v,
         string_agg(CASE WHEN (o.value_num >= 6) THEN o.oid || '|' || strftime(o.effective, '%Y-%m-%d') END, ';' ORDER BY o.effective, o.oid) AS ev
  FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -730) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code)) o GROUP BY pid, index_date),
-- ATOMS-INC-09 (inclusion): >=2 urate >= 6 in 2y
c_atoms_inc_09 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_09_1.v AS v,
         concat_ws(';', a_atoms_inc_09_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_09_1 ON a_atoms_inc_09_1.pid = b.pid AND a_atoms_inc_09_1.index_date = b.index_date),
a_atoms_inc_10_1 AS (
  SELECT pid, index_date, (o.value_num BETWEEN 5 AND 9) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- ATOMS-INC-10 (inclusion): latest urate between 5 and 9
c_atoms_inc_10 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_10_1.v AS v,
         concat_ws(';', a_atoms_inc_10_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_10_1 ON a_atoms_inc_10_1.pid = b.pid AND a_atoms_inc_10_1.index_date = b.index_date),
a_atoms_inc_11_1 AS (
  SELECT pid, index_date, (o.value_code IN ('LA6577-6')) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE <= b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBSAG' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- ATOMS-INC-11 (inclusion): latest HBsAg negative
c_atoms_inc_11 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_11_1.v AS v,
         concat_ws(';', a_atoms_inc_11_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_11_1 ON a_atoms_inc_11_1.pid = b.pid AND a_atoms_inc_11_1.index_date = b.index_date),
a_atoms_inc_12_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, oid AS rid, effective::DATE AS d FROM observation x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -180) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-12 (inclusion): urate tested in 6 months
c_atoms_inc_12 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_12_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_inc_12_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_12_1 ON a_atoms_inc_12_1.pid = b.pid AND a_atoms_inc_12_1.index_date = b.index_date),
a_atoms_inc_13_1 AS (
  SELECT pid, index_date, coalesce(bool_or((o.value_num >= 150)), FALSE) AS v,
         string_agg(CASE WHEN (o.value_num >= 150) THEN o.oid || '|' || strftime(o.effective, '%Y-%m-%d') END, ';' ORDER BY o.effective, o.oid) AS ev
  FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SYSTOLIC_BLOOD_PRESSURE' AND vs.system = o.system AND vs.code = o.code)) o GROUP BY pid, index_date),
-- ATOMS-INC-13 (inclusion): SBP any >= 150 in 1y (component)
c_atoms_inc_13 AS (
  SELECT b.pid, b.index_date, a_atoms_inc_13_1.v AS v,
         concat_ws(';', a_atoms_inc_13_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_13_1 ON a_atoms_inc_13_1.pid = b.pid AND a_atoms_inc_13_1.index_date = b.index_date),
a_atoms_inc_14_1_weight AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '29463-7') WHERE rn = 1),
a_atoms_inc_14_1_height AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '8302-2') WHERE rn = 1),
a_atoms_inc_14_1 AS (
  SELECT b.pid, b.index_date, weight.value_num / pow(height.value_num / 100.0, 2) AS val, concat_ws(';', weight.oid || '|' || strftime(weight.effective, '%Y-%m-%d'), height.oid || '|' || strftime(height.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_14_1_weight weight ON weight.pid = b.pid AND weight.index_date = b.index_date
  LEFT JOIN a_atoms_inc_14_1_height height ON height.pid = b.pid AND height.index_date = b.index_date),
-- ATOMS-INC-14 (inclusion): BMI computable
c_atoms_inc_14 AS (
  SELECT b.pid, b.index_date, (CASE WHEN a_atoms_inc_14_1.val IS NULL THEN NULL ELSE TRUE END) AS v,
         concat_ws(';', a_atoms_inc_14_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_14_1 ON a_atoms_inc_14_1.pid = b.pid AND a_atoms_inc_14_1.index_date = b.index_date),
a_atoms_inc_15_1_tjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'TJC28') WHERE rn = 1),
a_atoms_inc_15_1_sjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'SJC28') WHERE rn = 1),
a_atoms_inc_15_1_ptga AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'PTGA') WHERE rn = 1),
a_atoms_inc_15_1_esr AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '4537-7') WHERE rn = 1),
a_atoms_inc_15_1_crp AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '1988-5') WHERE rn = 1),
a_atoms_inc_15_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN tjc28.value_num IS NULL OR sjc28.value_num IS NULL OR ptga.value_num IS NULL THEN NULL WHEN esr.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.7 * ln(esr.value_num) WHEN crp.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.36 * ln(crp.value_num + 1) + 0.96 ELSE NULL END) AS val, concat_ws(';', tjc28.oid || '|' || strftime(tjc28.effective, '%Y-%m-%d'), sjc28.oid || '|' || strftime(sjc28.effective, '%Y-%m-%d'), ptga.oid || '|' || strftime(ptga.effective, '%Y-%m-%d'), esr.oid || '|' || strftime(esr.effective, '%Y-%m-%d'), crp.oid || '|' || strftime(crp.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_15_1_tjc28 tjc28 ON tjc28.pid = b.pid AND tjc28.index_date = b.index_date
  LEFT JOIN a_atoms_inc_15_1_sjc28 sjc28 ON sjc28.pid = b.pid AND sjc28.index_date = b.index_date
  LEFT JOIN a_atoms_inc_15_1_ptga ptga ON ptga.pid = b.pid AND ptga.index_date = b.index_date
  LEFT JOIN a_atoms_inc_15_1_esr esr ON esr.pid = b.pid AND esr.index_date = b.index_date
  LEFT JOIN a_atoms_inc_15_1_crp crp ON crp.pid = b.pid AND crp.index_date = b.index_date),
-- ATOMS-INC-15 (inclusion): DAS28 > 3.2 in 180 days
c_atoms_inc_15 AS (
  SELECT b.pid, b.index_date, (a_atoms_inc_15_1.val > 3.2) AS v,
         concat_ws(';', a_atoms_inc_15_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_15_1 ON a_atoms_inc_15_1.pid = b.pid AND a_atoms_inc_15_1.index_date = b.index_date),
a_atoms_inc_16_1_creatinine AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '2160-0') WHERE rn = 1),
a_atoms_inc_16_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN creatinine.value_num IS NULL OR date_sub('year', b.birth_date, b.index_date) IS NULL OR (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) IS NULL THEN NULL ELSE 142.0 * pow(least(creatinine.value_num / (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 0.7 ELSE 0.9 END), 1.0), (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN -0.241 ELSE -0.302 END)) * pow(greatest(creatinine.value_num / (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 0.7 ELSE 0.9 END), 1.0), -1.2) * pow(0.9938, date_sub('year', b.birth_date, b.index_date)) * (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 1.012 ELSE 1.0 END) END) AS val, concat_ws(';', creatinine.oid || '|' || strftime(creatinine.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_16_1_creatinine creatinine ON creatinine.pid = b.pid AND creatinine.index_date = b.index_date),
-- ATOMS-INC-16 (inclusion): eGFR between 30 and 90
c_atoms_inc_16 AS (
  SELECT b.pid, b.index_date, (a_atoms_inc_16_1.val BETWEEN 30 AND 90) AS v,
         concat_ws(';', a_atoms_inc_16_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_16_1 ON a_atoms_inc_16_1.pid = b.pid AND a_atoms_inc_16_1.index_date = b.index_date),
a_atoms_inc_17_1_p AS (
  SELECT b.pid, b.index_date, m.mid, greatest(coalesce(m.start, m.authored), (b.index_date + -730)) AS s,
         least(coalesce(m."end", m.start, m.authored), b.index_date) AS e
  FROM base b JOIN medication m ON m.pid = b.pid
  WHERE (EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_METHOTREXATE' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = m.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_METHOTREXATE' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = m.nhi_code))
    AND coalesce(m.start, m.authored) IS NOT NULL
    AND greatest(coalesce(m.start, m.authored), (b.index_date + -730)) <= least(coalesce(m."end", m.start, m.authored), b.index_date)),
a_atoms_inc_17_1_g AS (
  SELECT *, CASE WHEN s <= max(e) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) + 1 THEN 0 ELSE 1 END AS new_island
  FROM a_atoms_inc_17_1_p),
a_atoms_inc_17_1_i AS (
  SELECT *, sum(new_island) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS UNBOUNDED PRECEDING) AS island FROM a_atoms_inc_17_1_g),
a_atoms_inc_17_1 AS (
  SELECT pid, index_date, max(len) AS days, string_agg(ev, ';' ORDER BY ev) AS ev FROM (
    SELECT pid, index_date, island, (max(e) - min(s)) + 1 AS len,
           string_agg(mid, ';' ORDER BY s, mid) AS ev FROM a_atoms_inc_17_1_i GROUP BY pid, index_date, island)
  GROUP BY pid, index_date),
-- ATOMS-INC-17 (inclusion): MTX >=180 days gap 0 in 2y
c_atoms_inc_17 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_17_1.days, 0) >= 180) AS v,
         concat_ws(';', a_atoms_inc_17_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_17_1 ON a_atoms_inc_17_1.pid = b.pid AND a_atoms_inc_17_1.index_date = b.index_date),
a_atoms_inc_18_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_COLCHICINE' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_COLCHICINE' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-18 (inclusion): colchicine Rx in 1y
c_atoms_inc_18 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_18_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_inc_18_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_18_1 ON a_atoms_inc_18_1.pid = b.pid AND a_atoms_inc_18_1.index_date = b.index_date),
a_atoms_inc_19_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, rid, effective AS d FROM report x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_CHEST_X_RAY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -180) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-19 (inclusion): CXR report in 180 d
c_atoms_inc_19 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_19_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_inc_19_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_19_1 ON a_atoms_inc_19_1.pid = b.pid AND a_atoms_inc_19_1.index_date = b.index_date),
a_atoms_inc_20_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, kid AS rid, created AS d FROM claim x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RA_BIOLOGIC' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.product)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-20 (inclusion): biologic application in 365 d
c_atoms_inc_20 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_20_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_inc_20_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_20_1 ON a_atoms_inc_20_1.pid = b.pid AND a_atoms_inc_20_1.index_date = b.index_date),
a_atoms_inc_21_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, eid AS rid, start::DATE AS d FROM encounter x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RHEUMATOLOGY_CLINIC_VISIT' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/department' AND vs.code = x.dept)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-INC-21 (inclusion): >=3 RHEU visits in 1y
c_atoms_inc_21 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_inc_21_1.n, 0) >= 3) AS v,
         concat_ws(';', a_atoms_inc_21_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_inc_21_1 ON a_atoms_inc_21_1.pid = b.pid AND a_atoms_inc_21_1.index_date = b.index_date),
a_atoms_exc_22_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, prid AS rid, performed AS d FROM procedure x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_BARIATRIC_SURGERY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-EXC-22 (exclusion): bariatric surgery ever
c_atoms_exc_22 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_exc_22_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_exc_22_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_exc_22_1 ON a_atoms_exc_22_1.pid = b.pid AND a_atoms_exc_22_1.index_date = b.index_date),
a_atoms_exc_23_1 AS (
  SELECT pid, index_date, (o.value_code IN ('LA6576-8')) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE <= b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_IGRA' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
a_atoms_exc_23_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TB_PREVENTIVE_THERAPY' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TB_PREVENTIVE_THERAPY' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- ATOMS-EXC-23 (exclusion): IGRA positive and not on TB prophylaxis
c_atoms_exc_23 AS (
  SELECT b.pid, b.index_date, (a_atoms_exc_23_1.v AND (NOT (coalesce(a_atoms_exc_23_2.n, 0) > 0))) AS v,
         concat_ws(';', a_atoms_exc_23_1.ev, a_atoms_exc_23_2.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_exc_23_1 ON a_atoms_exc_23_1.pid = b.pid AND a_atoms_exc_23_1.index_date = b.index_date
  LEFT JOIN a_atoms_exc_23_2 ON a_atoms_exc_23_2.pid = b.pid AND a_atoms_exc_23_2.index_date = b.index_date),
a_atoms_exc_24_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TYPE_1_DIABETES_MELLITUS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
a_atoms_exc_24_3 AS (
  SELECT pid, index_date, (o.value_num > 10) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBA1C' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- ATOMS-EXC-24 (exclusion): T1DM or (male and HbA1c > 10)
c_atoms_exc_24 AS (
  SELECT b.pid, b.index_date, ((coalesce(a_atoms_exc_24_1.n, 0) > 0) OR (((CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'male' END)) AND a_atoms_exc_24_3.v)) AS v,
         concat_ws(';', a_atoms_exc_24_1.ev, NULL, a_atoms_exc_24_3.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_exc_24_1 ON a_atoms_exc_24_1.pid = b.pid AND a_atoms_exc_24_1.index_date = b.index_date
  LEFT JOIN a_atoms_exc_24_3 ON a_atoms_exc_24_3.pid = b.pid AND a_atoms_exc_24_3.index_date = b.index_date),
a_atoms_exc_25_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_COLCHICINE' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_COLCHICINE' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -10) AND (b.index_date + 10)
  GROUP BY b.pid, b.index_date),
-- ATOMS-EXC-25 (exclusion): future window: appointment-independent, med in [-10,+10]
c_atoms_exc_25 AS (
  SELECT b.pid, b.index_date, (coalesce(a_atoms_exc_25_1.n, 0) > 0) AS v,
         concat_ws(';', a_atoms_exc_25_1.ev) AS ev
  FROM base b
  LEFT JOIN a_atoms_exc_25_1 ON a_atoms_exc_25_1.pid = b.pid AND a_atoms_exc_25_1.index_date = b.index_date)
SELECT b.pid, b.index_date,
  c_atoms_inc_01.v AS "C_ATOMS-INC-01", c_atoms_inc_01.ev AS "E_ATOMS-INC-01",
  c_atoms_inc_02.v AS "C_ATOMS-INC-02", c_atoms_inc_02.ev AS "E_ATOMS-INC-02",
  c_atoms_inc_03.v AS "C_ATOMS-INC-03", c_atoms_inc_03.ev AS "E_ATOMS-INC-03",
  c_atoms_inc_04.v AS "C_ATOMS-INC-04", c_atoms_inc_04.ev AS "E_ATOMS-INC-04",
  c_atoms_inc_05.v AS "C_ATOMS-INC-05", c_atoms_inc_05.ev AS "E_ATOMS-INC-05",
  c_atoms_inc_06.v AS "C_ATOMS-INC-06", c_atoms_inc_06.ev AS "E_ATOMS-INC-06",
  c_atoms_inc_07.v AS "C_ATOMS-INC-07", c_atoms_inc_07.ev AS "E_ATOMS-INC-07",
  c_atoms_inc_08.v AS "C_ATOMS-INC-08", c_atoms_inc_08.ev AS "E_ATOMS-INC-08",
  c_atoms_inc_09.v AS "C_ATOMS-INC-09", c_atoms_inc_09.ev AS "E_ATOMS-INC-09",
  c_atoms_inc_10.v AS "C_ATOMS-INC-10", c_atoms_inc_10.ev AS "E_ATOMS-INC-10",
  c_atoms_inc_11.v AS "C_ATOMS-INC-11", c_atoms_inc_11.ev AS "E_ATOMS-INC-11",
  c_atoms_inc_12.v AS "C_ATOMS-INC-12", c_atoms_inc_12.ev AS "E_ATOMS-INC-12",
  c_atoms_inc_13.v AS "C_ATOMS-INC-13", c_atoms_inc_13.ev AS "E_ATOMS-INC-13",
  c_atoms_inc_14.v AS "C_ATOMS-INC-14", c_atoms_inc_14.ev AS "E_ATOMS-INC-14",
  c_atoms_inc_15.v AS "C_ATOMS-INC-15", c_atoms_inc_15.ev AS "E_ATOMS-INC-15",
  c_atoms_inc_16.v AS "C_ATOMS-INC-16", c_atoms_inc_16.ev AS "E_ATOMS-INC-16",
  c_atoms_inc_17.v AS "C_ATOMS-INC-17", c_atoms_inc_17.ev AS "E_ATOMS-INC-17",
  c_atoms_inc_18.v AS "C_ATOMS-INC-18", c_atoms_inc_18.ev AS "E_ATOMS-INC-18",
  c_atoms_inc_19.v AS "C_ATOMS-INC-19", c_atoms_inc_19.ev AS "E_ATOMS-INC-19",
  c_atoms_inc_20.v AS "C_ATOMS-INC-20", c_atoms_inc_20.ev AS "E_ATOMS-INC-20",
  c_atoms_inc_21.v AS "C_ATOMS-INC-21", c_atoms_inc_21.ev AS "E_ATOMS-INC-21",
  c_atoms_exc_22.v AS "C_ATOMS-EXC-22", c_atoms_exc_22.ev AS "E_ATOMS-EXC-22",
  c_atoms_exc_23.v AS "C_ATOMS-EXC-23", c_atoms_exc_23.ev AS "E_ATOMS-EXC-23",
  c_atoms_exc_24.v AS "C_ATOMS-EXC-24", c_atoms_exc_24.ev AS "E_ATOMS-EXC-24",
  c_atoms_exc_25.v AS "C_ATOMS-EXC-25", c_atoms_exc_25.ev AS "E_ATOMS-EXC-25"
FROM base b
LEFT JOIN c_atoms_inc_01 ON c_atoms_inc_01.pid = b.pid AND c_atoms_inc_01.index_date = b.index_date
LEFT JOIN c_atoms_inc_02 ON c_atoms_inc_02.pid = b.pid AND c_atoms_inc_02.index_date = b.index_date
LEFT JOIN c_atoms_inc_03 ON c_atoms_inc_03.pid = b.pid AND c_atoms_inc_03.index_date = b.index_date
LEFT JOIN c_atoms_inc_04 ON c_atoms_inc_04.pid = b.pid AND c_atoms_inc_04.index_date = b.index_date
LEFT JOIN c_atoms_inc_05 ON c_atoms_inc_05.pid = b.pid AND c_atoms_inc_05.index_date = b.index_date
LEFT JOIN c_atoms_inc_06 ON c_atoms_inc_06.pid = b.pid AND c_atoms_inc_06.index_date = b.index_date
LEFT JOIN c_atoms_inc_07 ON c_atoms_inc_07.pid = b.pid AND c_atoms_inc_07.index_date = b.index_date
LEFT JOIN c_atoms_inc_08 ON c_atoms_inc_08.pid = b.pid AND c_atoms_inc_08.index_date = b.index_date
LEFT JOIN c_atoms_inc_09 ON c_atoms_inc_09.pid = b.pid AND c_atoms_inc_09.index_date = b.index_date
LEFT JOIN c_atoms_inc_10 ON c_atoms_inc_10.pid = b.pid AND c_atoms_inc_10.index_date = b.index_date
LEFT JOIN c_atoms_inc_11 ON c_atoms_inc_11.pid = b.pid AND c_atoms_inc_11.index_date = b.index_date
LEFT JOIN c_atoms_inc_12 ON c_atoms_inc_12.pid = b.pid AND c_atoms_inc_12.index_date = b.index_date
LEFT JOIN c_atoms_inc_13 ON c_atoms_inc_13.pid = b.pid AND c_atoms_inc_13.index_date = b.index_date
LEFT JOIN c_atoms_inc_14 ON c_atoms_inc_14.pid = b.pid AND c_atoms_inc_14.index_date = b.index_date
LEFT JOIN c_atoms_inc_15 ON c_atoms_inc_15.pid = b.pid AND c_atoms_inc_15.index_date = b.index_date
LEFT JOIN c_atoms_inc_16 ON c_atoms_inc_16.pid = b.pid AND c_atoms_inc_16.index_date = b.index_date
LEFT JOIN c_atoms_inc_17 ON c_atoms_inc_17.pid = b.pid AND c_atoms_inc_17.index_date = b.index_date
LEFT JOIN c_atoms_inc_18 ON c_atoms_inc_18.pid = b.pid AND c_atoms_inc_18.index_date = b.index_date
LEFT JOIN c_atoms_inc_19 ON c_atoms_inc_19.pid = b.pid AND c_atoms_inc_19.index_date = b.index_date
LEFT JOIN c_atoms_inc_20 ON c_atoms_inc_20.pid = b.pid AND c_atoms_inc_20.index_date = b.index_date
LEFT JOIN c_atoms_inc_21 ON c_atoms_inc_21.pid = b.pid AND c_atoms_inc_21.index_date = b.index_date
LEFT JOIN c_atoms_exc_22 ON c_atoms_exc_22.pid = b.pid AND c_atoms_exc_22.index_date = b.index_date
LEFT JOIN c_atoms_exc_23 ON c_atoms_exc_23.pid = b.pid AND c_atoms_exc_23.index_date = b.index_date
LEFT JOIN c_atoms_exc_24 ON c_atoms_exc_24.pid = b.pid AND c_atoms_exc_24.index_date = b.index_date
LEFT JOIN c_atoms_exc_25 ON c_atoms_exc_25.pid = b.pid AND c_atoms_exc_25.index_date = b.index_date
ORDER BY b.pid, b.index_date
