-- RA-COH v1.0.0 — GENERATED by TrialBox criteria-compiler from Criterion IR (SPEC §6.3).
-- Deterministic template output; never edited by hand or produced by an LLM.
-- Parameters: $1 index_dates DATE[] ; $2 pids VARCHAR[] (NULL = all patients alive at index).
-- Output: one row per (pid, index_date) with "C_<ID>" BOOLEAN/NULL and "E_<ID>" VARCHAR per criterion.
WITH
params AS (SELECT CAST($1 AS DATE[]) AS idx_dates, CAST($2 AS VARCHAR[]) AS pids),
idx AS (SELECT unnest(idx_dates) AS index_date FROM params),
base AS (
  SELECT p.pid, p.birth_date, p.sex, i.index_date FROM patient p CROSS JOIN idx i
  WHERE ((SELECT pids FROM params) IS NULL OR list_contains((SELECT pids FROM params), p.pid))
    AND (p.deceased_date IS NULL OR p.deceased_date > i.index_date)
    AND (p.birth_date IS NULL OR p.birth_date <= i.index_date)),
vs(vs_id, system, code) AS (VALUES
  ('VS_HBSAG', 'http://loinc.org', '5196-1'),
  ('VS_METHOTREXATE', 'http://www.whocc.no/atc', 'L04AX03'),
  ('VS_RA_BIOLOGIC', 'http://www.whocc.no/atc', 'L04AB01'),
  ('VS_RA_BIOLOGIC', 'http://www.whocc.no/atc', 'L04AB04'),
  ('VS_RA_BIOLOGIC', 'http://www.whocc.no/atc', 'L04AC07'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M05.79'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M05.9'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M06.00'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M06.4'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M06.9')),
a_ra_coh_inc_01_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RHEUMATOID_ARTHRITIS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-COH-INC-01 (inclusion): 曾經診斷類風濕性關節炎（ICD-10-CM M05 或 M06）之病人。
c_ra_coh_inc_01 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_coh_inc_01_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_coh_inc_01_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_01_1 ON a_ra_coh_inc_01_1.pid = b.pid AND a_ra_coh_inc_01_1.index_date = b.index_date),
a_ra_coh_inc_02_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_METHOTREXATE' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_METHOTREXATE' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-COH-INC-02 (inclusion): 一年內曾使用 methotrexate。
c_ra_coh_inc_02 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_coh_inc_02_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_coh_inc_02_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_02_1 ON a_ra_coh_inc_02_1.pid = b.pid AND a_ra_coh_inc_02_1.index_date = b.index_date),
a_ra_coh_inc_03_1_tjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'TJC28') WHERE rn = 1),
a_ra_coh_inc_03_1_sjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'SJC28') WHERE rn = 1),
a_ra_coh_inc_03_1_ptga AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'PTGA') WHERE rn = 1),
a_ra_coh_inc_03_1_esr AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '4537-7') WHERE rn = 1),
a_ra_coh_inc_03_1_crp AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '1988-5') WHERE rn = 1),
a_ra_coh_inc_03_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN tjc28.value_num IS NULL OR sjc28.value_num IS NULL OR ptga.value_num IS NULL THEN NULL WHEN esr.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.7 * ln(esr.value_num) WHEN crp.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.36 * ln(crp.value_num + 1) + 0.96 ELSE NULL END) AS val, concat_ws(';', tjc28.oid || '|' || strftime(tjc28.effective, '%Y-%m-%d'), sjc28.oid || '|' || strftime(sjc28.effective, '%Y-%m-%d'), ptga.oid || '|' || strftime(ptga.effective, '%Y-%m-%d'), esr.oid || '|' || strftime(esr.effective, '%Y-%m-%d'), crp.oid || '|' || strftime(crp.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_03_1_tjc28 tjc28 ON tjc28.pid = b.pid AND tjc28.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_03_1_sjc28 sjc28 ON sjc28.pid = b.pid AND sjc28.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_03_1_ptga ptga ON ptga.pid = b.pid AND ptga.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_03_1_esr esr ON esr.pid = b.pid AND esr.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_03_1_crp crp ON crp.pid = b.pid AND crp.index_date = b.index_date),
-- RA-COH-INC-03 (inclusion): 九十日內最近一次 DAS28 大於 5.1（高疾病活動度）。
c_ra_coh_inc_03 AS (
  SELECT b.pid, b.index_date, (a_ra_coh_inc_03_1.val > 5.1) AS v,
         concat_ws(';', a_ra_coh_inc_03_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_03_1 ON a_ra_coh_inc_03_1.pid = b.pid AND a_ra_coh_inc_03_1.index_date = b.index_date),
a_ra_coh_inc_04_1_tjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'TJC28') WHERE rn = 1),
a_ra_coh_inc_04_1_sjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'SJC28') WHERE rn = 1),
a_ra_coh_inc_04_1_ptga AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'PTGA') WHERE rn = 1),
a_ra_coh_inc_04_1_esr AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '4537-7') WHERE rn = 1),
a_ra_coh_inc_04_1_crp AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '1988-5') WHERE rn = 1),
a_ra_coh_inc_04_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN tjc28.value_num IS NULL OR sjc28.value_num IS NULL OR ptga.value_num IS NULL THEN NULL WHEN esr.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.7 * ln(esr.value_num) WHEN crp.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.36 * ln(crp.value_num + 1) + 0.96 ELSE NULL END) AS val, concat_ws(';', tjc28.oid || '|' || strftime(tjc28.effective, '%Y-%m-%d'), sjc28.oid || '|' || strftime(sjc28.effective, '%Y-%m-%d'), ptga.oid || '|' || strftime(ptga.effective, '%Y-%m-%d'), esr.oid || '|' || strftime(esr.effective, '%Y-%m-%d'), crp.oid || '|' || strftime(crp.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_04_1_tjc28 tjc28 ON tjc28.pid = b.pid AND tjc28.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_04_1_sjc28 sjc28 ON sjc28.pid = b.pid AND sjc28.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_04_1_ptga ptga ON ptga.pid = b.pid AND ptga.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_04_1_esr esr ON esr.pid = b.pid AND esr.index_date = b.index_date
  LEFT JOIN a_ra_coh_inc_04_1_crp crp ON crp.pid = b.pid AND crp.index_date = b.index_date),
-- RA-COH-INC-04 (inclusion): 九十日內最近一次 DAS28 小於或等於 3.2（低疾病活動度）。
c_ra_coh_inc_04 AS (
  SELECT b.pid, b.index_date, (a_ra_coh_inc_04_1.val <= 3.2) AS v,
         concat_ws(';', a_ra_coh_inc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_04_1 ON a_ra_coh_inc_04_1.pid = b.pid AND a_ra_coh_inc_04_1.index_date = b.index_date),
a_ra_coh_inc_05_1 AS (
  SELECT pid, index_date, (o.value_code IN ('LA6576-8')) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE <= b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBSAG' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- RA-COH-INC-05 (inclusion): 最近一次 B 型肝炎表面抗原（HBsAg）陽性。
c_ra_coh_inc_05 AS (
  SELECT b.pid, b.index_date, a_ra_coh_inc_05_1.v AS v,
         concat_ws(';', a_ra_coh_inc_05_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_05_1 ON a_ra_coh_inc_05_1.pid = b.pid AND a_ra_coh_inc_05_1.index_date = b.index_date),
a_ra_coh_inc_06_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RA_BIOLOGIC' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RA_BIOLOGIC' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-COH-INC-06 (inclusion): 一年內曾使用生物製劑。
c_ra_coh_inc_06 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_coh_inc_06_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_coh_inc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_coh_inc_06_1 ON a_ra_coh_inc_06_1.pid = b.pid AND a_ra_coh_inc_06_1.index_date = b.index_date)
SELECT b.pid, b.index_date,
  c_ra_coh_inc_01.v AS "C_RA-COH-INC-01", c_ra_coh_inc_01.ev AS "E_RA-COH-INC-01",
  c_ra_coh_inc_02.v AS "C_RA-COH-INC-02", c_ra_coh_inc_02.ev AS "E_RA-COH-INC-02",
  c_ra_coh_inc_03.v AS "C_RA-COH-INC-03", c_ra_coh_inc_03.ev AS "E_RA-COH-INC-03",
  c_ra_coh_inc_04.v AS "C_RA-COH-INC-04", c_ra_coh_inc_04.ev AS "E_RA-COH-INC-04",
  c_ra_coh_inc_05.v AS "C_RA-COH-INC-05", c_ra_coh_inc_05.ev AS "E_RA-COH-INC-05",
  c_ra_coh_inc_06.v AS "C_RA-COH-INC-06", c_ra_coh_inc_06.ev AS "E_RA-COH-INC-06"
FROM base b
LEFT JOIN c_ra_coh_inc_01 ON c_ra_coh_inc_01.pid = b.pid AND c_ra_coh_inc_01.index_date = b.index_date
LEFT JOIN c_ra_coh_inc_02 ON c_ra_coh_inc_02.pid = b.pid AND c_ra_coh_inc_02.index_date = b.index_date
LEFT JOIN c_ra_coh_inc_03 ON c_ra_coh_inc_03.pid = b.pid AND c_ra_coh_inc_03.index_date = b.index_date
LEFT JOIN c_ra_coh_inc_04 ON c_ra_coh_inc_04.pid = b.pid AND c_ra_coh_inc_04.index_date = b.index_date
LEFT JOIN c_ra_coh_inc_05 ON c_ra_coh_inc_05.pid = b.pid AND c_ra_coh_inc_05.index_date = b.index_date
LEFT JOIN c_ra_coh_inc_06 ON c_ra_coh_inc_06.pid = b.pid AND c_ra_coh_inc_06.index_date = b.index_date
ORDER BY b.pid, b.index_date
