"""IR -> DuckDB SQL (SPEC §6.3). One CTE per atom and one per criterion; output one row per (pid, index_date) with
``"C_<ID>"`` (BOOLEAN or NULL) and ``"E_<ID>"`` (evidence VARCHAR) columns. Template-based and deterministic.

Runtime parameters (positional, in this order): ``index_dates`` (DATE[] / ISO strings) and ``pids`` (VARCHAR[] or
NULL for every living patient). ValueSet codes are inlined as a ``vs`` VALUES CTE so the SQL file is self-contained.
"""

from __future__ import annotations

from tb_common.derived import ASDAS, CODES, COMPONENTS, DAS28, EGFR
from tb_contracts import Atom, BoolExpr, CriterionIR

from criteria_compiler.semantics import (
    CompileError,
    Kind,
    Window,
    atoms,
    check_bool,
    compiled,
    fmt_num,
    ident,
    kind,
    window,
)
from criteria_compiler.terminology.mapper import SYSTEMS, ValueSets

HEADER = """-- {ruleset} v{version} — GENERATED by TrialBox criteria-compiler from Criterion IR (SPEC §6.3).
-- Deterministic template output; never edited by hand or produced by an LLM.
-- Parameters: $1 index_dates DATE[] ; $2 pids VARCHAR[] (NULL = all patients alive at index).
-- Output: one row per (pid, index_date) with "C_<ID>" BOOLEAN/NULL and "E_<ID>" VARCHAR per criterion.
"""


def lit(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def qcol(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def date_bound(days: int) -> str:
    return "b.index_date" if days == 0 else f"(b.index_date + {days})"


def in_window(col: str, w: Window) -> str:
    hi = date_bound(w.to_days)
    if w.from_days is None:
        return f"{col} <= {hi}"
    return f"{col} BETWEEN {date_bound(w.from_days)} AND {hi}"


def cmp_sql(atom: Atom, value: str = "o.value_num", code: str = "o.value_code") -> str:
    v = atom.value
    assert v is not None and v.op is not None
    if v.op == "in":
        return f"({code} IN ({', '.join(lit(c) for c in v.codes or [])}))"
    if v.op == "between":
        assert v.num is not None and v.num2 is not None
        return f"({value} BETWEEN {fmt_num(v.num)} AND {fmt_num(v.num2)})"
    assert v.num is not None
    op = "=" if v.op == "=" else v.op
    return f"({value} {op} {fmt_num(v.num)})"


class SqlGenerator:
    def __init__(self, ruleset: str, version: str, valuesets: ValueSets) -> None:
        self.ruleset = ruleset
        self.version = version
        self.vs = valuesets

    def _vs_match(self, vsname: str, system_col: str, code_col: str) -> str:
        return (
            f"EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = {lit(vsname)} AND vs.system = {system_col} "
            f"AND vs.code = {code_col})"
        )

    # ------------------------------------------------------------------ per-atom CTEs; returns (ctes, expr, ev)
    def _presence(self, name: str, atom: Atom, w: Window) -> tuple[list[str], str, str]:
        vsn = atom.valueset
        match atom.domain:
            case "condition":
                src = (
                    f"SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x "
                    f"WHERE {self._vs_match(vsn, 'x.system', 'x.code')}"
                )
            case "medication":
                src = (
                    f"SELECT pid, mid AS rid, authored AS d FROM medication x WHERE "
                    f"{self._vs_match(vsn, lit(SYSTEMS['atc']), 'x.atc')} OR "
                    f"{self._vs_match(vsn, lit(SYSTEMS['nhi_drug']), 'x.nhi_code')}"
                )
            case "procedure":
                src = (
                    f"SELECT pid, prid AS rid, performed AS d FROM procedure x "
                    f"WHERE {self._vs_match(vsn, 'x.system', 'x.code')}"
                )
            case "report":
                src = f"SELECT pid, rid, effective AS d FROM report x WHERE {self._vs_match(vsn, 'x.system', 'x.code')}"
            case "observation":
                src = (
                    f"SELECT pid, oid AS rid, effective::DATE AS d FROM observation x "
                    f"WHERE {self._vs_match(vsn, 'x.system', 'x.code')}"
                )
            case "encounter":
                src = (
                    f"SELECT pid, eid AS rid, start::DATE AS d FROM encounter x "
                    f"WHERE {self._vs_match(vsn, lit(SYSTEMS['department']), 'x.dept')}"
                )
            case "claim":
                src = (
                    f"SELECT pid, kid AS rid, created AS d FROM claim x "
                    f"WHERE {self._vs_match(vsn, lit(SYSTEMS['nhi_drug']), 'x.product')}"
                )
            case _:
                raise CompileError(f"unsupported domain {atom.domain}")
        cte = (
            f"{name} AS (\n  SELECT b.pid, b.index_date, count(*) AS n,\n"
            f"         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev\n"
            f"  FROM base b JOIN ({src}) e ON e.pid = b.pid AND {in_window('e.d', w)}\n"
            f"  GROUP BY b.pid, b.index_date)"
        )
        quant = atom.quantifier or "any"
        n = f"coalesce({name}.n, 0)"
        if quant == "count>=":
            expr = f"({n} >= {atom.count})"
        elif quant == "none":
            expr = f"({n} = 0)"
        else:
            expr = f"({n} > 0)"
        return [cte], expr, f"{name}.ev"

    def _obs_source(self, vsname: str, w: Window) -> str:
        return (
            f"SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code\n"
            f"  FROM base b JOIN observation o ON o.pid = b.pid AND {in_window('o.effective::DATE', w)}\n"
            f"  WHERE {self._vs_match(vsname, 'o.system', 'o.code')}"
        )

    def _obs_value(self, name: str, atom: Atom, w: Window) -> tuple[list[str], str, str]:
        quant = atom.quantifier or "any"
        src = self._obs_source(atom.valueset, w)
        if quant == "latest":
            cte = (
                f"{name} AS (\n  SELECT pid, index_date, {cmp_sql(atom)} AS v,\n"
                f"         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev\n"
                f"  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, "
                f"oid DESC) AS rn\n        FROM ({src})) o WHERE rn = 1)"
            )
            return [cte], f"{name}.v", f"{name}.ev"
        c = cmp_sql(atom)
        if quant == "any":
            agg = f"coalesce(bool_or({c}), FALSE)"
        elif quant == "none":
            agg = f"NOT coalesce(bool_or({c}), FALSE)"
        elif quant == "all":
            agg = f"coalesce(bool_and({c}), TRUE)"
        elif quant == "count>=":
            agg = f"(count(*) FILTER (WHERE {c}) >= {atom.count})"
        else:
            raise CompileError(f"quantifier {quant}")
        cte = (
            f"{name} AS (\n  SELECT pid, index_date, {agg} AS v,\n"
            f"         string_agg(CASE WHEN {c} THEN o.oid || '|' || strftime(o.effective, '%Y-%m-%d') END, ';' "
            f"ORDER BY o.effective, o.oid) AS ev\n"
            f"  FROM ({src}) o GROUP BY pid, index_date)"
        )
        return [cte], f"{name}.v", f"{name}.ev"

    def _latest_component(self, name: str, comp: str, w: Window) -> str:
        system, code = CODES[comp]
        return (
            f"{name}_{comp} AS (\n  SELECT pid, index_date, value_num, oid, effective FROM (\n"
            f"    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,\n"
            f"           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC)"
            f" AS rn\n    FROM base b JOIN observation o ON o.pid = b.pid AND {in_window('o.effective::DATE', w)}\n"
            f"    WHERE o.system = {lit(system)} AND o.code = {lit(code)}) WHERE rn = 1)"
        )

    def _derived(self, name: str, atom: Atom, w: Window) -> tuple[list[str], str, str]:
        assert atom.derived is not None
        comps = COMPONENTS[atom.derived]
        ctes = [self._latest_component(name, comp, w) for comp in comps]
        joins = "\n  ".join(
            f"LEFT JOIN {name}_{c} {c} ON {c}.pid = b.pid AND {c}.index_date = b.index_date" for c in comps
        )
        v = {c: f"{c}.value_num" for c in comps}
        match atom.derived:
            case "bmi":
                value = f"{v['weight']} / pow({v['height']} / 100.0, 2)"
            case "egfr":
                female = "(CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END)"
                age = "date_sub('year', b.birth_date, b.index_date)"
                kappa = f"(CASE WHEN {female} THEN {EGFR['kappa_f']} ELSE {EGFR['kappa_m']} END)"
                alpha = f"(CASE WHEN {female} THEN {EGFR['alpha_f']} ELSE {EGFR['alpha_m']} END)"
                # least()/greatest() ignore NULLs in DuckDB: guard every input explicitly (CQL does the same)
                value = (
                    f"(CASE WHEN {v['creatinine']} IS NULL OR {age} IS NULL OR {female} IS NULL THEN NULL "
                    f"ELSE {EGFR['k']} * pow(least({v['creatinine']} / {kappa}, 1.0), {alpha}) * "
                    f"pow(greatest({v['creatinine']} / {kappa}, 1.0), {EGFR['exp_hi']}) * "
                    f"pow({EGFR['age_base']}, {age}) * (CASE WHEN {female} THEN {EGFR['female']} ELSE 1.0 END) "
                    f"END)"
                )
            case "das28":
                base = (
                    f"{DAS28['tjc']} * sqrt({v['tjc28']}) + {DAS28['sjc']} * sqrt({v['sjc28']}) + "
                    f"{DAS28['gh']} * {v['ptga']}"
                )
                value = (
                    f"(CASE WHEN {v['tjc28']} IS NULL OR {v['sjc28']} IS NULL OR {v['ptga']} IS NULL THEN NULL "
                    f"WHEN {v['esr']} IS NOT NULL THEN {base} + {DAS28['esr_ln']} * ln({v['esr']}) "
                    f"WHEN {v['crp']} IS NOT NULL THEN {base} + {DAS28['crp_ln']} * ln({v['crp']} + 1) + "
                    f"{DAS28['crp_const']} ELSE NULL END)"
                )
            case "basdai":
                q = [v[f"basdai_q{i}"] for i in range(1, 7)]
                value = f"(({q[0]} + {q[1]} + {q[2]} + {q[3]} + ({q[4]} + {q[5]}) / 2.0) / 5.0)"
            case "asdas":
                value = (
                    f"({ASDAS['back']} * {v['basdai_q2']} + {ASDAS['stiff']} * {v['basdai_q6']} + "
                    f"{ASDAS['ptga']} * ({v['ptga']} / 10.0) + {ASDAS['periph']} * {v['basdai_q3']} + "
                    f"{ASDAS['crp_ln']} * ln({v['crp']} + 1))"
                )
            case _:
                raise CompileError(f"derived {atom.derived}")
        ev = (
            "concat_ws(';', " + ", ".join(f"{c}.oid || '|' || strftime({c}.effective, '%Y-%m-%d')" for c in comps) + ")"
        )
        ctes.append(f"{name} AS (\n  SELECT b.pid, b.index_date, {value} AS val, {ev} AS ev\n  FROM base b\n  {joins})")
        expr = (
            cmp_sql(atom, value=f"{name}.val")
            if atom.value is not None
            else f"(CASE WHEN {name}.val IS NULL THEN NULL ELSE TRUE END)"
        )
        return ctes, expr, f"{name}.ev"

    def _med_duration(self, name: str, atom: Atom, w: Window) -> tuple[list[str], str, str]:
        assert atom.duration is not None and atom.duration.min_days is not None
        gap = 30 if atom.duration.gap_days is None else atom.duration.gap_days
        lo = "DATE '1900-01-01'" if w.from_days is None else date_bound(w.from_days)
        hi = date_bound(w.to_days)
        match = (
            f"({self._vs_match(atom.valueset, lit(SYSTEMS['atc']), 'm.atc')} OR "
            f"{self._vs_match(atom.valueset, lit(SYSTEMS['nhi_drug']), 'm.nhi_code')})"
        )
        ctes = [
            (
                f"{name}_p AS (\n  SELECT b.pid, b.index_date, m.mid, greatest(coalesce(m.start, m.authored), {lo}) AS s,\n"
                f'         least(coalesce(m."end", m.start, m.authored), {hi}) AS e\n'
                f"  FROM base b JOIN medication m ON m.pid = b.pid\n  WHERE {match}\n"
                f'    AND greatest(coalesce(m.start, m.authored), {lo}) <= least(coalesce(m."end", m.start, m.authored), '
                f"{hi}))"
            ),
            (
                f"{name}_g AS (\n  SELECT *, CASE WHEN s <= max(e) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid "
                f"ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) + {gap + 1} THEN 0 ELSE 1 END AS new_island\n"
                f"  FROM {name}_p)"
            ),
            (
                f"{name}_i AS (\n  SELECT *, sum(new_island) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid "
                f"ROWS UNBOUNDED PRECEDING) AS island FROM {name}_g)"
            ),
            (
                f"{name} AS (\n  SELECT pid, index_date, max(len) AS days, "
                f"string_agg(ev, ';' ORDER BY ev) AS ev FROM (\n"
                f"    SELECT pid, index_date, island, (max(e) - min(s)) + 1 AS len,\n"
                f"           string_agg(mid, ';' ORDER BY s, mid) AS ev FROM {name}_i GROUP BY pid, index_date, island)\n"
                f"  GROUP BY pid, index_date)"
            ),
        ]
        return ctes, f"(coalesce({name}.days, 0) >= {atom.duration.min_days})", f"{name}.ev"

    def _demographic(self, atom: Atom) -> tuple[list[str], str, str]:
        conds = []
        age = "date_sub('year', b.birth_date, b.index_date)"
        if atom.age is not None:
            if atom.age.min is not None:
                conds.append(f"({age} >= {fmt_num(atom.age.min)})")
            if atom.age.max is not None:
                conds.append(f"({age} <= {fmt_num(atom.age.max)})")
        if atom.sex is not None:
            conds.append(f"(CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = {lit(atom.sex)} END)")
        return [], "(" + " AND ".join(conds) + ")", "NULL"

    # ------------------------------------------------------------------ assembly
    def _bool(self, expr: Atom | BoolExpr, names: dict[int, str]) -> str:
        if isinstance(expr, Atom):
            return names[id(expr)]
        parts = [self._bool(a, names) for a in expr.args]
        if expr.op == "not":
            return f"(NOT {parts[0]})"
        return "(" + f" {expr.op.upper()} ".join(parts) + ")"

    def render(self, criteria: list[CriterionIR]) -> str:
        ctes: list[str] = []
        selects: list[str] = []
        final_joins: list[str] = []
        used_vs: set[str] = set()
        for c in compiled(criteria):
            check_bool(c.logic)
            names: dict[int, str] = {}
            evs: list[str] = []
            joins: list[str] = []
            for n, atom in enumerate(atoms(c.logic), start=1):
                k = kind(atom)
                w = window(atom)
                aname = f"a_{ident(c.id)}_{n}".lower()
                if k is Kind.PRESENCE:
                    cs, expr, ev = self._presence(aname, atom, w)
                elif k is Kind.OBS_VALUE:
                    cs, expr, ev = self._obs_value(aname, atom, w)
                elif k is Kind.DERIVED:
                    cs, expr, ev = self._derived(aname, atom, w)
                elif k is Kind.MED_DURATION:
                    cs, expr, ev = self._med_duration(aname, atom, w)
                else:
                    cs, expr, ev = self._demographic(atom)
                if atom.domain != "demographic" and atom.derived is None:
                    used_vs.add(atom.valueset)
                ctes.extend(cs)
                if cs:
                    joins.append(f"LEFT JOIN {aname} ON {aname}.pid = b.pid AND {aname}.index_date = b.index_date")
                names[id(atom)] = expr
                evs.append(ev)
            crit = f"c_{ident(c.id)}".lower()
            ctes.append(
                f"-- {c.id} ({c.kind}): {c.text.strip()[:150]}\n{crit} AS (\n"
                f"  SELECT b.pid, b.index_date, {self._bool(c.logic, names)} AS v,\n"
                f"         concat_ws(';', {', '.join(evs)}) AS ev\n  FROM base b\n  "
                + ("\n  ".join(joins) if joins else "")
                + ")"
            )
            selects.append(f"{crit}.v AS {qcol('C_' + c.id)}, {crit}.ev AS {qcol('E_' + c.id)}")
            final_joins.append(f"LEFT JOIN {crit} ON {crit}.pid = b.pid AND {crit}.index_date = b.index_date")
        vs_rows = []
        for v in sorted(used_vs):
            for system, code in self.vs.codes(v):
                vs_rows.append(f"({lit(v)}, {lit(system)}, {lit(code)})")
        if not vs_rows:
            vs_rows.append("('__none__', '', '')")
        prelude = [
            "params AS (SELECT CAST($1 AS DATE[]) AS idx_dates, CAST($2 AS VARCHAR[]) AS pids)",
            "idx AS (SELECT unnest(idx_dates) AS index_date FROM params)",
            (
                "base AS (\n  SELECT p.pid, p.birth_date, p.sex, i.index_date FROM patient p CROSS JOIN idx i\n"
                "  WHERE ((SELECT pids FROM params) IS NULL OR list_contains((SELECT pids FROM params), p.pid))\n"
                "    AND (p.deceased_date IS NULL OR p.deceased_date > i.index_date)\n"
                "    AND (p.birth_date IS NULL OR p.birth_date <= i.index_date))"
            ),
            "vs(vs_id, system, code) AS (VALUES\n  " + ",\n  ".join(vs_rows) + ")",
        ]
        body = ",\n".join(prelude + ctes)
        return (
            HEADER.format(ruleset=self.ruleset, version=self.version)
            + "WITH\n"
            + body
            + "\nSELECT b.pid, b.index_date,\n  "
            + ",\n  ".join(selects)
            + "\nFROM base b\n"
            + "\n".join(final_joins)
            + "\nORDER BY b.pid, b.index_date\n"
        )
