-- GZQO v1.0.0 — GENERATED by TrialBox criteria-compiler from Criterion IR (SPEC §6.3).
-- Deterministic template output; never edited by hand or produced by an LLM.
-- Parameters: $1 index_dates DATE[] ; $2 pids VARCHAR[] (NULL = all patients alive at index).
-- Output: one row per (pid, index_date) with "C_<ID>" BOOLEAN/NULL and "E_<ID>" VARCHAR per criterion.
WITH
params AS (SELECT CAST($1 AS DATE[]) AS idx_dates, CAST($2 AS VARCHAR[]) AS pids),
idx AS (SELECT unnest(idx_dates) AS index_date FROM params),
base AS (
  SELECT p.pid, p.birth_date, p.sex, i.index_date FROM patient p CROSS JOIN idx i
  WHERE ((SELECT pids FROM params) IS NULL OR list_contains((SELECT pids FROM params), p.pid))
    AND (p.deceased_date IS NULL OR p.deceased_date > i.index_date)
    AND (p.birth_date IS NULL OR p.birth_date <= i.index_date)),
vs(vs_id, system, code) AS (VALUES
  ('VS_ACUTE_OR_CHRONIC_PANCREATITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'K85.20'),
  ('VS_ACUTE_OR_CHRONIC_PANCREATITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'K85.90'),
  ('VS_ACUTE_OR_CHRONIC_PANCREATITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'K86.0'),
  ('VS_ACUTE_OR_CHRONIC_PANCREATITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'K86.1'),
  ('VS_ALT', 'http://loinc.org', '1742-6'),
  ('VS_BARIATRIC_SURGERY', 'https://trialbox.local/fhir/CodeSystem/nhi-order', '75613B'),
  ('VS_BARIATRIC_SURGERY', 'https://trialbox.local/fhir/CodeSystem/nhi-order', '75614B'),
  ('VS_GLP_1_RECEPTOR_AGONIST', 'http://www.whocc.no/atc', 'A10BJ02'),
  ('VS_GLP_1_RECEPTOR_AGONIST', 'http://www.whocc.no/atc', 'A10BJ05'),
  ('VS_GLP_1_RECEPTOR_AGONIST', 'http://www.whocc.no/atc', 'A10BJ06'),
  ('VS_GLP_1_RECEPTOR_AGONIST', 'http://www.whocc.no/atc', 'A10BX16'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.00'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.071'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.072'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.9'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.00X0'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.9XX0'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.9XX1'),
  ('VS_HBA1C', 'http://loinc.org', '4548-4'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C16.9'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C18.9'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C22.0'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C34.11'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C34.90'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C50.911'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C61'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C73'),
  ('VS_MEDULLARY_THYROID_CARCINOMA', 'http://hl7.org/fhir/sid/icd-10-cm', 'C73'),
  ('VS_MULTIPLE_ENDOCRINE_NEOPLASIA_TYPE_2', 'http://hl7.org/fhir/sid/icd-10-cm', 'E31.22'),
  ('VS_MULTIPLE_ENDOCRINE_NEOPLASIA_TYPE_2', 'http://hl7.org/fhir/sid/icd-10-cm', 'E31.23'),
  ('VS_MYOCARDIAL_INFARCTION', 'http://hl7.org/fhir/sid/icd-10-cm', 'I21.4'),
  ('VS_MYOCARDIAL_INFARCTION', 'http://hl7.org/fhir/sid/icd-10-cm', 'I21.9'),
  ('VS_PREGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'Z33.1'),
  ('VS_PREGNANCY_TEST', 'http://loinc.org', '2106-3'),
  ('VS_RHEUMATOLOGY_OR_METABOLISM_CLINIC_VISIT', 'https://trialbox.local/fhir/CodeSystem/department', 'META'),
  ('VS_RHEUMATOLOGY_OR_METABOLISM_CLINIC_VISIT', 'https://trialbox.local/fhir/CodeSystem/department', 'RHEU'),
  ('VS_SERUM_URATE', 'http://loinc.org', '3084-1'),
  ('VS_STROKE', 'http://hl7.org/fhir/sid/icd-10-cm', 'I63.50'),
  ('VS_STROKE', 'http://hl7.org/fhir/sid/icd-10-cm', 'I63.9'),
  ('VS_SYSTOLIC_BLOOD_PRESSURE', 'http://loinc.org', '8480-6'),
  ('VS_TYPE_1_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E10.10'),
  ('VS_TYPE_1_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E10.65'),
  ('VS_TYPE_1_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E10.9'),
  ('VS_URATE_LOWERING_THERAPY', 'http://www.whocc.no/atc', 'M04AA01'),
  ('VS_URATE_LOWERING_THERAPY', 'http://www.whocc.no/atc', 'M04AA03'),
  ('VS_URATE_LOWERING_THERAPY', 'http://www.whocc.no/atc', 'M04AB03')),
-- GZQO-INC-01 (inclusion): Male or female participants aged 18 years or older at screening.
c_gzqo_inc_01 AS (
  SELECT b.pid, b.index_date, ((date_sub('year', b.birth_date, b.index_date) >= 18)) AS v,
         concat_ws(';', NULL) AS ev
  FROM base b
  ),
a_gzqo_inc_02_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GOUT' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-INC-02 (inclusion): Diagnosis of gout according to the 2015 ACR/EULAR gout classification criteria.
c_gzqo_inc_02 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_inc_02_1.n, 0) > 0) AS v,
         concat_ws(';', a_gzqo_inc_02_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_02_1 ON a_gzqo_inc_02_1.pid = b.pid AND a_gzqo_inc_02_1.index_date = b.index_date),
a_gzqo_inc_03_1_weight AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '29463-7') WHERE rn = 1),
a_gzqo_inc_03_1_height AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '8302-2') WHERE rn = 1),
a_gzqo_inc_03_1 AS (
  SELECT b.pid, b.index_date, weight.value_num / pow(height.value_num / 100.0, 2) AS val, concat_ws(';', weight.oid || '|' || strftime(weight.effective, '%Y-%m-%d'), height.oid || '|' || strftime(height.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_03_1_weight weight ON weight.pid = b.pid AND weight.index_date = b.index_date
  LEFT JOIN a_gzqo_inc_03_1_height height ON height.pid = b.pid AND height.index_date = b.index_date),
-- GZQO-INC-03 (inclusion): Body mass index (BMI) ≥27 kg/m² at screening.
c_gzqo_inc_03 AS (
  SELECT b.pid, b.index_date, (a_gzqo_inc_03_1.val >= 27) AS v,
         concat_ws(';', a_gzqo_inc_03_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_03_1 ON a_gzqo_inc_03_1.pid = b.pid AND a_gzqo_inc_03_1.index_date = b.index_date),
a_gzqo_inc_04_1 AS (
  SELECT pid, index_date, (o.value_num >= 6.8) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
a_gzqo_inc_04_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_URATE_LOWERING_THERAPY' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_URATE_LOWERING_THERAPY' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -90) AND b.index_date
  GROUP BY b.pid, b.index_date),
a_gzqo_inc_04_3 AS (
  SELECT pid, index_date, (o.value_num >= 6) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- GZQO-INC-04 (inclusion): Serum urate ≥6.8 mg/dL at screening, or ≥6.0 mg/dL if receiving urate-lowering therapy.
c_gzqo_inc_04 AS (
  SELECT b.pid, b.index_date, (a_gzqo_inc_04_1.v OR ((coalesce(a_gzqo_inc_04_2.n, 0) > 0) AND a_gzqo_inc_04_3.v)) AS v,
         concat_ws(';', a_gzqo_inc_04_1.ev, a_gzqo_inc_04_2.ev, a_gzqo_inc_04_3.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_04_1 ON a_gzqo_inc_04_1.pid = b.pid AND a_gzqo_inc_04_1.index_date = b.index_date
  LEFT JOIN a_gzqo_inc_04_2 ON a_gzqo_inc_04_2.pid = b.pid AND a_gzqo_inc_04_2.index_date = b.index_date
  LEFT JOIN a_gzqo_inc_04_3 ON a_gzqo_inc_04_3.pid = b.pid AND a_gzqo_inc_04_3.index_date = b.index_date),
a_gzqo_inc_06_1_p AS (
  SELECT b.pid, b.index_date, m.mid, greatest(coalesce(m.start, m.authored), (b.index_date + -180)) AS s,
         least(coalesce(m."end", m.start, m.authored), b.index_date) AS e
  FROM base b JOIN medication m ON m.pid = b.pid
  WHERE (EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_URATE_LOWERING_THERAPY' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = m.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_URATE_LOWERING_THERAPY' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = m.nhi_code))
    AND greatest(coalesce(m.start, m.authored), (b.index_date + -180)) <= least(coalesce(m."end", m.start, m.authored), b.index_date)),
a_gzqo_inc_06_1_g AS (
  SELECT *, CASE WHEN s <= max(e) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) + 31 THEN 0 ELSE 1 END AS new_island
  FROM a_gzqo_inc_06_1_p),
a_gzqo_inc_06_1_i AS (
  SELECT *, sum(new_island) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS UNBOUNDED PRECEDING) AS island FROM a_gzqo_inc_06_1_g),
a_gzqo_inc_06_1 AS (
  SELECT pid, index_date, max(len) AS days, string_agg(ev, ';' ORDER BY ev) AS ev FROM (
    SELECT pid, index_date, island, (max(e) - min(s)) + 1 AS len,
           string_agg(mid, ';' ORDER BY s, mid) AS ev FROM a_gzqo_inc_06_1_i GROUP BY pid, index_date, island)
  GROUP BY pid, index_date),
-- GZQO-INC-06 (inclusion): Receiving stable urate-lowering therapy for at least 3 months (continuous within the past 6 months, gaps ≤30 days).
c_gzqo_inc_06 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_inc_06_1.days, 0) >= 90) AS v,
         concat_ws(';', a_gzqo_inc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_06_1 ON a_gzqo_inc_06_1.pid = b.pid AND a_gzqo_inc_06_1.index_date = b.index_date),
a_gzqo_inc_08_1_creatinine AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '2160-0') WHERE rn = 1),
a_gzqo_inc_08_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN creatinine.value_num IS NULL OR date_sub('year', b.birth_date, b.index_date) IS NULL OR (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) IS NULL THEN NULL ELSE 142.0 * pow(least(creatinine.value_num / (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 0.7 ELSE 0.9 END), 1.0), (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN -0.241 ELSE -0.302 END)) * pow(greatest(creatinine.value_num / (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 0.7 ELSE 0.9 END), 1.0), -1.2) * pow(0.9938, date_sub('year', b.birth_date, b.index_date)) * (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 1.012 ELSE 1.0 END) END) AS val, concat_ws(';', creatinine.oid || '|' || strftime(creatinine.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_08_1_creatinine creatinine ON creatinine.pid = b.pid AND creatinine.index_date = b.index_date),
-- GZQO-INC-08 (inclusion): Estimated GFR ≥30 mL/min/1.73 m² (CKD-EPI 2021) at screening.
c_gzqo_inc_08 AS (
  SELECT b.pid, b.index_date, (a_gzqo_inc_08_1.val >= 30) AS v,
         concat_ws(';', a_gzqo_inc_08_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_08_1 ON a_gzqo_inc_08_1.pid = b.pid AND a_gzqo_inc_08_1.index_date = b.index_date),
a_gzqo_inc_09_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, eid AS rid, start::DATE AS d FROM encounter x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RHEUMATOLOGY_OR_METABOLISM_CLINIC_VISIT' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/department' AND vs.code = x.dept)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-INC-09 (inclusion): Followed at the rheumatology or metabolism clinic with at least one visit in the past 12 months.
c_gzqo_inc_09 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_inc_09_1.n, 0) >= 1) AS v,
         concat_ws(';', a_gzqo_inc_09_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_inc_09_1 ON a_gzqo_inc_09_1.pid = b.pid AND a_gzqo_inc_09_1.index_date = b.index_date),
a_gzqo_exc_01_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TYPE_1_DIABETES_MELLITUS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-01 (exclusion): Type 1 diabetes mellitus.
c_gzqo_exc_01 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_exc_01_1.n, 0) > 0) AS v,
         concat_ws(';', a_gzqo_exc_01_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_01_1 ON a_gzqo_exc_01_1.pid = b.pid AND a_gzqo_exc_01_1.index_date = b.index_date),
a_gzqo_exc_02_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_ACUTE_OR_CHRONIC_PANCREATITIS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-02 (exclusion): History of acute or chronic pancreatitis.
c_gzqo_exc_02 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_exc_02_1.n, 0) > 0) AS v,
         concat_ws(';', a_gzqo_exc_02_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_02_1 ON a_gzqo_exc_02_1.pid = b.pid AND a_gzqo_exc_02_1.index_date = b.index_date),
a_gzqo_exc_03_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_MEDULLARY_THYROID_CARCINOMA' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
a_gzqo_exc_03_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_MULTIPLE_ENDOCRINE_NEOPLASIA_TYPE_2' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-03 (exclusion): Personal history of medullary thyroid carcinoma or multiple endocrine neoplasia type 2.
c_gzqo_exc_03 AS (
  SELECT b.pid, b.index_date, ((coalesce(a_gzqo_exc_03_1.n, 0) > 0) OR (coalesce(a_gzqo_exc_03_2.n, 0) > 0)) AS v,
         concat_ws(';', a_gzqo_exc_03_1.ev, a_gzqo_exc_03_2.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_03_1 ON a_gzqo_exc_03_1.pid = b.pid AND a_gzqo_exc_03_1.index_date = b.index_date
  LEFT JOIN a_gzqo_exc_03_2 ON a_gzqo_exc_03_2.pid = b.pid AND a_gzqo_exc_03_2.index_date = b.index_date),
a_gzqo_exc_04_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GLP_1_RECEPTOR_AGONIST' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GLP_1_RECEPTOR_AGONIST' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -90) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-04 (exclusion): Use of a GLP-1 receptor agonist or GIP/GLP-1 receptor agonist within 90 days before screening.
c_gzqo_exc_04 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_exc_04_1.n, 0) > 0) AS v,
         concat_ws(';', a_gzqo_exc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_04_1 ON a_gzqo_exc_04_1.pid = b.pid AND a_gzqo_exc_04_1.index_date = b.index_date),
a_gzqo_exc_05_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, prid AS rid, performed AS d FROM procedure x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_BARIATRIC_SURGERY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-05 (exclusion): Prior or planned bariatric surgery.
c_gzqo_exc_05 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_exc_05_1.n, 0) > 0) AS v,
         concat_ws(';', a_gzqo_exc_05_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_05_1 ON a_gzqo_exc_05_1.pid = b.pid AND a_gzqo_exc_05_1.index_date = b.index_date),
a_gzqo_exc_06_1 AS (
  SELECT pid, index_date, (o.value_num > 10) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBA1C' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- GZQO-EXC-06 (exclusion): HbA1c >10% at screening.
c_gzqo_exc_06 AS (
  SELECT b.pid, b.index_date, a_gzqo_exc_06_1.v AS v,
         concat_ws(';', a_gzqo_exc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_06_1 ON a_gzqo_exc_06_1.pid = b.pid AND a_gzqo_exc_06_1.index_date = b.index_date),
a_gzqo_exc_07_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_MALIGNANCY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -1825) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-07 (exclusion): Malignancy within the past 5 years, except non-melanoma skin cancer.
c_gzqo_exc_07 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gzqo_exc_07_1.n, 0) > 0) AS v,
         concat_ws(';', a_gzqo_exc_07_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_07_1 ON a_gzqo_exc_07_1.pid = b.pid AND a_gzqo_exc_07_1.index_date = b.index_date),
a_gzqo_exc_08_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_PREGNANCY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -280) AND b.index_date
  GROUP BY b.pid, b.index_date),
a_gzqo_exc_08_3 AS (
  SELECT pid, index_date, (o.value_code IN ('LA6576-8')) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -30) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_PREGNANCY_TEST' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- GZQO-EXC-08 (exclusion): Pregnant or breastfeeding, or positive pregnancy test.
c_gzqo_exc_08 AS (
  SELECT b.pid, b.index_date, ((coalesce(a_gzqo_exc_08_1.n, 0) > 0) OR (((CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END)) AND a_gzqo_exc_08_3.v)) AS v,
         concat_ws(';', a_gzqo_exc_08_1.ev, NULL, a_gzqo_exc_08_3.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_08_1 ON a_gzqo_exc_08_1.pid = b.pid AND a_gzqo_exc_08_1.index_date = b.index_date
  LEFT JOIN a_gzqo_exc_08_3 ON a_gzqo_exc_08_3.pid = b.pid AND a_gzqo_exc_08_3.index_date = b.index_date),
a_gzqo_exc_09_1 AS (
  SELECT pid, index_date, (o.value_num >= 160) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SYSTOLIC_BLOOD_PRESSURE' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- GZQO-EXC-09 (exclusion): Uncontrolled hypertension (systolic blood pressure ≥160 mmHg) at screening.
c_gzqo_exc_09 AS (
  SELECT b.pid, b.index_date, a_gzqo_exc_09_1.v AS v,
         concat_ws(';', a_gzqo_exc_09_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_09_1 ON a_gzqo_exc_09_1.pid = b.pid AND a_gzqo_exc_09_1.index_date = b.index_date),
a_gzqo_exc_10_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_MYOCARDIAL_INFARCTION' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -90) AND b.index_date
  GROUP BY b.pid, b.index_date),
a_gzqo_exc_10_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_STROKE' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -90) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- GZQO-EXC-10 (exclusion): Myocardial infarction or stroke within 90 days before screening.
c_gzqo_exc_10 AS (
  SELECT b.pid, b.index_date, ((coalesce(a_gzqo_exc_10_1.n, 0) > 0) OR (coalesce(a_gzqo_exc_10_2.n, 0) > 0)) AS v,
         concat_ws(';', a_gzqo_exc_10_1.ev, a_gzqo_exc_10_2.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_10_1 ON a_gzqo_exc_10_1.pid = b.pid AND a_gzqo_exc_10_1.index_date = b.index_date
  LEFT JOIN a_gzqo_exc_10_2 ON a_gzqo_exc_10_2.pid = b.pid AND a_gzqo_exc_10_2.index_date = b.index_date),
a_gzqo_exc_13_1 AS (
  SELECT pid, index_date, (o.value_num > 120) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_ALT' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- GZQO-EXC-13 (exclusion): ALT >3× upper limit of normal (>120 U/L) at screening.
c_gzqo_exc_13 AS (
  SELECT b.pid, b.index_date, a_gzqo_exc_13_1.v AS v,
         concat_ws(';', a_gzqo_exc_13_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gzqo_exc_13_1 ON a_gzqo_exc_13_1.pid = b.pid AND a_gzqo_exc_13_1.index_date = b.index_date)
SELECT b.pid, b.index_date,
  c_gzqo_inc_01.v AS "C_GZQO-INC-01", c_gzqo_inc_01.ev AS "E_GZQO-INC-01",
  c_gzqo_inc_02.v AS "C_GZQO-INC-02", c_gzqo_inc_02.ev AS "E_GZQO-INC-02",
  c_gzqo_inc_03.v AS "C_GZQO-INC-03", c_gzqo_inc_03.ev AS "E_GZQO-INC-03",
  c_gzqo_inc_04.v AS "C_GZQO-INC-04", c_gzqo_inc_04.ev AS "E_GZQO-INC-04",
  c_gzqo_inc_06.v AS "C_GZQO-INC-06", c_gzqo_inc_06.ev AS "E_GZQO-INC-06",
  c_gzqo_inc_08.v AS "C_GZQO-INC-08", c_gzqo_inc_08.ev AS "E_GZQO-INC-08",
  c_gzqo_inc_09.v AS "C_GZQO-INC-09", c_gzqo_inc_09.ev AS "E_GZQO-INC-09",
  c_gzqo_exc_01.v AS "C_GZQO-EXC-01", c_gzqo_exc_01.ev AS "E_GZQO-EXC-01",
  c_gzqo_exc_02.v AS "C_GZQO-EXC-02", c_gzqo_exc_02.ev AS "E_GZQO-EXC-02",
  c_gzqo_exc_03.v AS "C_GZQO-EXC-03", c_gzqo_exc_03.ev AS "E_GZQO-EXC-03",
  c_gzqo_exc_04.v AS "C_GZQO-EXC-04", c_gzqo_exc_04.ev AS "E_GZQO-EXC-04",
  c_gzqo_exc_05.v AS "C_GZQO-EXC-05", c_gzqo_exc_05.ev AS "E_GZQO-EXC-05",
  c_gzqo_exc_06.v AS "C_GZQO-EXC-06", c_gzqo_exc_06.ev AS "E_GZQO-EXC-06",
  c_gzqo_exc_07.v AS "C_GZQO-EXC-07", c_gzqo_exc_07.ev AS "E_GZQO-EXC-07",
  c_gzqo_exc_08.v AS "C_GZQO-EXC-08", c_gzqo_exc_08.ev AS "E_GZQO-EXC-08",
  c_gzqo_exc_09.v AS "C_GZQO-EXC-09", c_gzqo_exc_09.ev AS "E_GZQO-EXC-09",
  c_gzqo_exc_10.v AS "C_GZQO-EXC-10", c_gzqo_exc_10.ev AS "E_GZQO-EXC-10",
  c_gzqo_exc_13.v AS "C_GZQO-EXC-13", c_gzqo_exc_13.ev AS "E_GZQO-EXC-13"
FROM base b
LEFT JOIN c_gzqo_inc_01 ON c_gzqo_inc_01.pid = b.pid AND c_gzqo_inc_01.index_date = b.index_date
LEFT JOIN c_gzqo_inc_02 ON c_gzqo_inc_02.pid = b.pid AND c_gzqo_inc_02.index_date = b.index_date
LEFT JOIN c_gzqo_inc_03 ON c_gzqo_inc_03.pid = b.pid AND c_gzqo_inc_03.index_date = b.index_date
LEFT JOIN c_gzqo_inc_04 ON c_gzqo_inc_04.pid = b.pid AND c_gzqo_inc_04.index_date = b.index_date
LEFT JOIN c_gzqo_inc_06 ON c_gzqo_inc_06.pid = b.pid AND c_gzqo_inc_06.index_date = b.index_date
LEFT JOIN c_gzqo_inc_08 ON c_gzqo_inc_08.pid = b.pid AND c_gzqo_inc_08.index_date = b.index_date
LEFT JOIN c_gzqo_inc_09 ON c_gzqo_inc_09.pid = b.pid AND c_gzqo_inc_09.index_date = b.index_date
LEFT JOIN c_gzqo_exc_01 ON c_gzqo_exc_01.pid = b.pid AND c_gzqo_exc_01.index_date = b.index_date
LEFT JOIN c_gzqo_exc_02 ON c_gzqo_exc_02.pid = b.pid AND c_gzqo_exc_02.index_date = b.index_date
LEFT JOIN c_gzqo_exc_03 ON c_gzqo_exc_03.pid = b.pid AND c_gzqo_exc_03.index_date = b.index_date
LEFT JOIN c_gzqo_exc_04 ON c_gzqo_exc_04.pid = b.pid AND c_gzqo_exc_04.index_date = b.index_date
LEFT JOIN c_gzqo_exc_05 ON c_gzqo_exc_05.pid = b.pid AND c_gzqo_exc_05.index_date = b.index_date
LEFT JOIN c_gzqo_exc_06 ON c_gzqo_exc_06.pid = b.pid AND c_gzqo_exc_06.index_date = b.index_date
LEFT JOIN c_gzqo_exc_07 ON c_gzqo_exc_07.pid = b.pid AND c_gzqo_exc_07.index_date = b.index_date
LEFT JOIN c_gzqo_exc_08 ON c_gzqo_exc_08.pid = b.pid AND c_gzqo_exc_08.index_date = b.index_date
LEFT JOIN c_gzqo_exc_09 ON c_gzqo_exc_09.pid = b.pid AND c_gzqo_exc_09.index_date = b.index_date
LEFT JOIN c_gzqo_exc_10 ON c_gzqo_exc_10.pid = b.pid AND c_gzqo_exc_10.index_date = b.index_date
LEFT JOIN c_gzqo_exc_13 ON c_gzqo_exc_13.pid = b.pid AND c_gzqo_exc_13.index_date = b.index_date
ORDER BY b.pid, b.index_date
