-- GOUT-COH v1.0.0 — GENERATED by TrialBox criteria-compiler from Criterion IR (SPEC §6.3).
-- Deterministic template output; never edited by hand or produced by an LLM.
-- Parameters: $1 index_dates DATE[] ; $2 pids VARCHAR[] (NULL = all patients alive at index).
-- Output: one row per (pid, index_date) with "C_<ID>" BOOLEAN/NULL and "E_<ID>" VARCHAR per criterion.
WITH
params AS (SELECT CAST($1 AS DATE[]) AS idx_dates, CAST($2 AS VARCHAR[]) AS pids),
idx AS (SELECT unnest(idx_dates) AS index_date FROM params),
base AS (
  SELECT p.pid, p.birth_date, p.sex, i.index_date FROM patient p CROSS JOIN idx i
  WHERE ((SELECT pids FROM params) IS NULL OR list_contains((SELECT pids FROM params), p.pid))
    AND (p.deceased_date IS NULL OR p.deceased_date > i.index_date)
    AND (p.birth_date IS NULL OR p.birth_date <= i.index_date)),
vs(vs_id, system, code) AS (VALUES
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.00'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.071'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.072'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M10.9'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.00X0'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.9XX0'),
  ('VS_GOUT', 'http://hl7.org/fhir/sid/icd-10-cm', 'M1A.9XX1'),
  ('VS_SERUM_URATE', 'http://loinc.org', '3084-1'),
  ('VS_TYPE_2_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E11.65'),
  ('VS_TYPE_2_DIABETES_MELLITUS', 'http://hl7.org/fhir/sid/icd-10-cm', 'E11.9'),
  ('VS_URATE_LOWERING_THERAPY', 'http://www.whocc.no/atc', 'M04AA01'),
  ('VS_URATE_LOWERING_THERAPY', 'http://www.whocc.no/atc', 'M04AA03'),
  ('VS_URATE_LOWERING_THERAPY', 'http://www.whocc.no/atc', 'M04AB03')),
a_gout_coh_inc_01_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GOUT' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GOUT-COH-INC-01 (inclusion): 曾經診斷痛風（ICD-10-CM M10 或 M1A）之病人。
c_gout_coh_inc_01 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gout_coh_inc_01_1.n, 0) > 0) AS v,
         concat_ws(';', a_gout_coh_inc_01_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_01_1 ON a_gout_coh_inc_01_1.pid = b.pid AND a_gout_coh_inc_01_1.index_date = b.index_date),
a_gout_coh_inc_02_1 AS (
  SELECT pid, index_date, (o.value_num >= 6) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERUM_URATE' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
-- GOUT-COH-INC-02 (inclusion): 一年內最近一次血清尿酸值大於或等於 6.0 mg/dL。
c_gout_coh_inc_02 AS (
  SELECT b.pid, b.index_date, a_gout_coh_inc_02_1.v AS v,
         concat_ws(';', a_gout_coh_inc_02_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_02_1 ON a_gout_coh_inc_02_1.pid = b.pid AND a_gout_coh_inc_02_1.index_date = b.index_date),
a_gout_coh_inc_03_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_URATE_LOWERING_THERAPY' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_URATE_LOWERING_THERAPY' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -180) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- GOUT-COH-INC-03 (inclusion): 六個月內曾使用降尿酸藥物。
c_gout_coh_inc_03 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gout_coh_inc_03_1.n, 0) > 0) AS v,
         concat_ws(';', a_gout_coh_inc_03_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_03_1 ON a_gout_coh_inc_03_1.pid = b.pid AND a_gout_coh_inc_03_1.index_date = b.index_date),
a_gout_coh_inc_04_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_GOUT' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- GOUT-COH-INC-04 (inclusion): 一年內因痛風就診二次以上。
c_gout_coh_inc_04 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gout_coh_inc_04_1.n, 0) >= 2) AS v,
         concat_ws(';', a_gout_coh_inc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_04_1 ON a_gout_coh_inc_04_1.pid = b.pid AND a_gout_coh_inc_04_1.index_date = b.index_date),
a_gout_coh_inc_05_1_creatinine AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '2160-0') WHERE rn = 1),
a_gout_coh_inc_05_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN creatinine.value_num IS NULL OR date_sub('year', b.birth_date, b.index_date) IS NULL OR (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) IS NULL THEN NULL ELSE 142.0 * pow(least(creatinine.value_num / (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 0.7 ELSE 0.9 END), 1.0), (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN -0.241 ELSE -0.302 END)) * pow(greatest(creatinine.value_num / (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 0.7 ELSE 0.9 END), 1.0), -1.2) * pow(0.9938, date_sub('year', b.birth_date, b.index_date)) * (CASE WHEN (CASE WHEN b.sex IS NULL THEN NULL ELSE b.sex = 'female' END) THEN 1.012 ELSE 1.0 END) END) AS val, concat_ws(';', creatinine.oid || '|' || strftime(creatinine.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_05_1_creatinine creatinine ON creatinine.pid = b.pid AND creatinine.index_date = b.index_date),
-- GOUT-COH-INC-05 (inclusion): 一年內最近一次 eGFR 小於 60 mL/min/1.73m²（慢性腎臟病第三期以上）。
c_gout_coh_inc_05 AS (
  SELECT b.pid, b.index_date, (a_gout_coh_inc_05_1.val < 60) AS v,
         concat_ws(';', a_gout_coh_inc_05_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_05_1 ON a_gout_coh_inc_05_1.pid = b.pid AND a_gout_coh_inc_05_1.index_date = b.index_date),
a_gout_coh_inc_06_1_weight AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '29463-7') WHERE rn = 1),
a_gout_coh_inc_06_1_height AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '8302-2') WHERE rn = 1),
a_gout_coh_inc_06_1 AS (
  SELECT b.pid, b.index_date, weight.value_num / pow(height.value_num / 100.0, 2) AS val, concat_ws(';', weight.oid || '|' || strftime(weight.effective, '%Y-%m-%d'), height.oid || '|' || strftime(height.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_06_1_weight weight ON weight.pid = b.pid AND weight.index_date = b.index_date
  LEFT JOIN a_gout_coh_inc_06_1_height height ON height.pid = b.pid AND height.index_date = b.index_date),
-- GOUT-COH-INC-06 (inclusion): 一年內最近一次身體質量指數大於或等於 27 kg/m²。
c_gout_coh_inc_06 AS (
  SELECT b.pid, b.index_date, (a_gout_coh_inc_06_1.val >= 27) AS v,
         concat_ws(';', a_gout_coh_inc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_06_1 ON a_gout_coh_inc_06_1.pid = b.pid AND a_gout_coh_inc_06_1.index_date = b.index_date),
a_gout_coh_inc_07_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TYPE_2_DIABETES_MELLITUS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- GOUT-COH-INC-07 (inclusion): 合併第二型糖尿病診斷。
c_gout_coh_inc_07 AS (
  SELECT b.pid, b.index_date, (coalesce(a_gout_coh_inc_07_1.n, 0) > 0) AS v,
         concat_ws(';', a_gout_coh_inc_07_1.ev) AS ev
  FROM base b
  LEFT JOIN a_gout_coh_inc_07_1 ON a_gout_coh_inc_07_1.pid = b.pid AND a_gout_coh_inc_07_1.index_date = b.index_date)
SELECT b.pid, b.index_date,
  c_gout_coh_inc_01.v AS "C_GOUT-COH-INC-01", c_gout_coh_inc_01.ev AS "E_GOUT-COH-INC-01",
  c_gout_coh_inc_02.v AS "C_GOUT-COH-INC-02", c_gout_coh_inc_02.ev AS "E_GOUT-COH-INC-02",
  c_gout_coh_inc_03.v AS "C_GOUT-COH-INC-03", c_gout_coh_inc_03.ev AS "E_GOUT-COH-INC-03",
  c_gout_coh_inc_04.v AS "C_GOUT-COH-INC-04", c_gout_coh_inc_04.ev AS "E_GOUT-COH-INC-04",
  c_gout_coh_inc_05.v AS "C_GOUT-COH-INC-05", c_gout_coh_inc_05.ev AS "E_GOUT-COH-INC-05",
  c_gout_coh_inc_06.v AS "C_GOUT-COH-INC-06", c_gout_coh_inc_06.ev AS "E_GOUT-COH-INC-06",
  c_gout_coh_inc_07.v AS "C_GOUT-COH-INC-07", c_gout_coh_inc_07.ev AS "E_GOUT-COH-INC-07"
FROM base b
LEFT JOIN c_gout_coh_inc_01 ON c_gout_coh_inc_01.pid = b.pid AND c_gout_coh_inc_01.index_date = b.index_date
LEFT JOIN c_gout_coh_inc_02 ON c_gout_coh_inc_02.pid = b.pid AND c_gout_coh_inc_02.index_date = b.index_date
LEFT JOIN c_gout_coh_inc_03 ON c_gout_coh_inc_03.pid = b.pid AND c_gout_coh_inc_03.index_date = b.index_date
LEFT JOIN c_gout_coh_inc_04 ON c_gout_coh_inc_04.pid = b.pid AND c_gout_coh_inc_04.index_date = b.index_date
LEFT JOIN c_gout_coh_inc_05 ON c_gout_coh_inc_05.pid = b.pid AND c_gout_coh_inc_05.index_date = b.index_date
LEFT JOIN c_gout_coh_inc_06 ON c_gout_coh_inc_06.pid = b.pid AND c_gout_coh_inc_06.index_date = b.index_date
LEFT JOIN c_gout_coh_inc_07 ON c_gout_coh_inc_07.pid = b.pid AND c_gout_coh_inc_07.index_date = b.index_date
ORDER BY b.pid, b.index_date
