-- RA-BIO v1.0.0 — GENERATED by TrialBox criteria-compiler from Criterion IR (SPEC §6.3).
-- Deterministic template output; never edited by hand or produced by an LLM.
-- Parameters: $1 index_dates DATE[] ; $2 pids VARCHAR[] (NULL = all patients alive at index).
-- Output: one row per (pid, index_date) with "C_<ID>" BOOLEAN/NULL and "E_<ID>" VARCHAR per criterion.
WITH
params AS (SELECT CAST($1 AS DATE[]) AS idx_dates, CAST($2 AS VARCHAR[]) AS pids),
idx AS (SELECT unnest(idx_dates) AS index_date FROM params),
base AS (
  SELECT p.pid, p.birth_date, p.sex, i.index_date FROM patient p CROSS JOIN idx i
  WHERE ((SELECT pids FROM params) IS NULL OR list_contains((SELECT pids FROM params), p.pid))
    AND (p.deceased_date IS NULL OR p.deceased_date > i.index_date)
    AND (p.birth_date IS NULL OR p.birth_date <= i.index_date)),
vs(vs_id, system, code) AS (VALUES
  ('VS_ACTIVE_TUBERCULOSIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'A15.0'),
  ('VS_ACTIVE_TUBERCULOSIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'A15.9'),
  ('VS_ACTIVE_TUBERCULOSIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'A19.9'),
  ('VS_ANTI_HBC', 'http://loinc.org', '16933-4'),
  ('VS_CHEST_X_RAY', 'http://loinc.org', '36643-5'),
  ('VS_CONVENTIONAL_SYNTHETIC_DMARD_OTHER_THAN_METHOTREXATE', 'http://www.whocc.no/atc', 'A07EC01'),
  ('VS_CONVENTIONAL_SYNTHETIC_DMARD_OTHER_THAN_METHOTREXATE', 'http://www.whocc.no/atc', 'L04AA13'),
  ('VS_CONVENTIONAL_SYNTHETIC_DMARD_OTHER_THAN_METHOTREXATE', 'http://www.whocc.no/atc', 'P01BA02'),
  ('VS_ESR_OR_CRP', 'http://loinc.org', '1988-5'),
  ('VS_ESR_OR_CRP', 'http://loinc.org', '4537-7'),
  ('VS_HBSAG', 'http://loinc.org', '5196-1'),
  ('VS_HBV_ANTIVIRAL_PROPHYLAXIS', 'http://www.whocc.no/atc', 'J05AF07'),
  ('VS_HBV_ANTIVIRAL_PROPHYLAXIS', 'http://www.whocc.no/atc', 'J05AF10'),
  ('VS_HEART_FAILURE', 'http://hl7.org/fhir/sid/icd-10-cm', 'I50.22'),
  ('VS_HEART_FAILURE', 'http://hl7.org/fhir/sid/icd-10-cm', 'I50.9'),
  ('VS_IGRA', 'http://loinc.org', '71774-4'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C16.9'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C18.9'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C22.0'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C34.11'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C34.90'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C50.911'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C61'),
  ('VS_MALIGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'C73'),
  ('VS_METHOTREXATE', 'http://www.whocc.no/atc', 'L04AX03'),
  ('VS_PREGNANCY', 'http://hl7.org/fhir/sid/icd-10-cm', 'Z33.1'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M05.79'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M05.9'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M06.00'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M06.4'),
  ('VS_RHEUMATOID_ARTHRITIS', 'http://hl7.org/fhir/sid/icd-10-cm', 'M06.9'),
  ('VS_SERIOUS_INFECTION', 'http://hl7.org/fhir/sid/icd-10-cm', 'A41.9'),
  ('VS_SERIOUS_INFECTION', 'http://hl7.org/fhir/sid/icd-10-cm', 'J18.9'),
  ('VS_TB_PREVENTIVE_THERAPY', 'http://www.whocc.no/atc', 'J04AB05'),
  ('VS_TB_PREVENTIVE_THERAPY', 'http://www.whocc.no/atc', 'J04AC01')),
-- RA-BIO-INC-01 (inclusion): 病患年齡須滿十八歲。
c_ra_bio_inc_01 AS (
  SELECT b.pid, b.index_date, ((date_sub('year', b.birth_date, b.index_date) >= 18)) AS v,
         concat_ws(';', NULL) AS ev
  FROM base b
  ),
a_ra_bio_inc_02_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_RHEUMATOID_ARTHRITIS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= (b.index_date + -180)
  GROUP BY b.pid, b.index_date),
-- RA-BIO-INC-02 (inclusion): 經診斷為類風濕關節炎且病程達六個月以上。
c_ra_bio_inc_02 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_inc_02_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_inc_02_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_02_1 ON a_ra_bio_inc_02_1.pid = b.pid AND a_ra_bio_inc_02_1.index_date = b.index_date),
a_ra_bio_inc_03_1_p AS (
  SELECT b.pid, b.index_date, m.mid, greatest(coalesce(m.start, m.authored), (b.index_date + -730)) AS s,
         least(coalesce(m."end", m.start, m.authored), b.index_date) AS e
  FROM base b JOIN medication m ON m.pid = b.pid
  WHERE (EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_METHOTREXATE' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = m.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_METHOTREXATE' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = m.nhi_code))
    AND greatest(coalesce(m.start, m.authored), (b.index_date + -730)) <= least(coalesce(m."end", m.start, m.authored), b.index_date)),
a_ra_bio_inc_03_1_g AS (
  SELECT *, CASE WHEN s <= max(e) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) + 31 THEN 0 ELSE 1 END AS new_island
  FROM a_ra_bio_inc_03_1_p),
a_ra_bio_inc_03_1_i AS (
  SELECT *, sum(new_island) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS UNBOUNDED PRECEDING) AS island FROM a_ra_bio_inc_03_1_g),
a_ra_bio_inc_03_1 AS (
  SELECT pid, index_date, max(len) AS days, string_agg(ev, ';' ORDER BY ev) AS ev FROM (
    SELECT pid, index_date, island, (max(e) - min(s)) + 1 AS len,
           string_agg(mid, ';' ORDER BY s, mid) AS ev FROM a_ra_bio_inc_03_1_i GROUP BY pid, index_date, island)
  GROUP BY pid, index_date),
-- RA-BIO-INC-03 (inclusion): 曾使用 methotrexate 治療至少六個月（連續使用，中斷不超過三十日）而療效不彰。
c_ra_bio_inc_03 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_inc_03_1.days, 0) >= 180) AS v,
         concat_ws(';', a_ra_bio_inc_03_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_03_1 ON a_ra_bio_inc_03_1.pid = b.pid AND a_ra_bio_inc_03_1.index_date = b.index_date),
a_ra_bio_inc_04_1_p AS (
  SELECT b.pid, b.index_date, m.mid, greatest(coalesce(m.start, m.authored), (b.index_date + -730)) AS s,
         least(coalesce(m."end", m.start, m.authored), b.index_date) AS e
  FROM base b JOIN medication m ON m.pid = b.pid
  WHERE (EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_CONVENTIONAL_SYNTHETIC_DMARD_OTHER_THAN_METHOTREXATE' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = m.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_CONVENTIONAL_SYNTHETIC_DMARD_OTHER_THAN_METHOTREXATE' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = m.nhi_code))
    AND greatest(coalesce(m.start, m.authored), (b.index_date + -730)) <= least(coalesce(m."end", m.start, m.authored), b.index_date)),
a_ra_bio_inc_04_1_g AS (
  SELECT *, CASE WHEN s <= max(e) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) + 31 THEN 0 ELSE 1 END AS new_island
  FROM a_ra_bio_inc_04_1_p),
a_ra_bio_inc_04_1_i AS (
  SELECT *, sum(new_island) OVER (PARTITION BY pid, index_date ORDER BY s, e, mid ROWS UNBOUNDED PRECEDING) AS island FROM a_ra_bio_inc_04_1_g),
a_ra_bio_inc_04_1 AS (
  SELECT pid, index_date, max(len) AS days, string_agg(ev, ';' ORDER BY ev) AS ev FROM (
    SELECT pid, index_date, island, (max(e) - min(s)) + 1 AS len,
           string_agg(mid, ';' ORDER BY s, mid) AS ev FROM a_ra_bio_inc_04_1_i GROUP BY pid, index_date, island)
  GROUP BY pid, index_date),
-- RA-BIO-INC-04 (inclusion): 曾使用 methotrexate 以外之另一種傳統型疾病修飾抗風濕藥物至少六個月（中斷不超過三十日）而療效不彰。
c_ra_bio_inc_04 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_inc_04_1.days, 0) >= 180) AS v,
         concat_ws(';', a_ra_bio_inc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_04_1 ON a_ra_bio_inc_04_1.pid = b.pid AND a_ra_bio_inc_04_1.index_date = b.index_date),
a_ra_bio_inc_05_1_tjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'TJC28') WHERE rn = 1),
a_ra_bio_inc_05_1_sjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'SJC28') WHERE rn = 1),
a_ra_bio_inc_05_1_ptga AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'PTGA') WHERE rn = 1),
a_ra_bio_inc_05_1_esr AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '4537-7') WHERE rn = 1),
a_ra_bio_inc_05_1_crp AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '1988-5') WHERE rn = 1),
a_ra_bio_inc_05_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN tjc28.value_num IS NULL OR sjc28.value_num IS NULL OR ptga.value_num IS NULL THEN NULL WHEN esr.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.7 * ln(esr.value_num) WHEN crp.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.36 * ln(crp.value_num + 1) + 0.96 ELSE NULL END) AS val, concat_ws(';', tjc28.oid || '|' || strftime(tjc28.effective, '%Y-%m-%d'), sjc28.oid || '|' || strftime(sjc28.effective, '%Y-%m-%d'), ptga.oid || '|' || strftime(ptga.effective, '%Y-%m-%d'), esr.oid || '|' || strftime(esr.effective, '%Y-%m-%d'), crp.oid || '|' || strftime(crp.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_05_1_tjc28 tjc28 ON tjc28.pid = b.pid AND tjc28.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_05_1_sjc28 sjc28 ON sjc28.pid = b.pid AND sjc28.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_05_1_ptga ptga ON ptga.pid = b.pid AND ptga.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_05_1_esr esr ON esr.pid = b.pid AND esr.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_05_1_crp crp ON crp.pid = b.pid AND crp.index_date = b.index_date),
-- RA-BIO-INC-05 (inclusion): 申請前九十日內之疾病活動度 DAS28 大於5.1。
c_ra_bio_inc_05 AS (
  SELECT b.pid, b.index_date, (a_ra_bio_inc_05_1.val > 5.1) AS v,
         concat_ws(';', a_ra_bio_inc_05_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_05_1 ON a_ra_bio_inc_05_1.pid = b.pid AND a_ra_bio_inc_05_1.index_date = b.index_date),
a_ra_bio_inc_06_1_tjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND (b.index_date + -90)
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'TJC28') WHERE rn = 1),
a_ra_bio_inc_06_1_sjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND (b.index_date + -90)
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'SJC28') WHERE rn = 1),
a_ra_bio_inc_06_1_ptga AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND (b.index_date + -90)
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'PTGA') WHERE rn = 1),
a_ra_bio_inc_06_1_esr AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND (b.index_date + -90)
    WHERE o.system = 'http://loinc.org' AND o.code = '4537-7') WHERE rn = 1),
a_ra_bio_inc_06_1_crp AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -180) AND (b.index_date + -90)
    WHERE o.system = 'http://loinc.org' AND o.code = '1988-5') WHERE rn = 1),
a_ra_bio_inc_06_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN tjc28.value_num IS NULL OR sjc28.value_num IS NULL OR ptga.value_num IS NULL THEN NULL WHEN esr.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.7 * ln(esr.value_num) WHEN crp.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.36 * ln(crp.value_num + 1) + 0.96 ELSE NULL END) AS val, concat_ws(';', tjc28.oid || '|' || strftime(tjc28.effective, '%Y-%m-%d'), sjc28.oid || '|' || strftime(sjc28.effective, '%Y-%m-%d'), ptga.oid || '|' || strftime(ptga.effective, '%Y-%m-%d'), esr.oid || '|' || strftime(esr.effective, '%Y-%m-%d'), crp.oid || '|' || strftime(crp.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_06_1_tjc28 tjc28 ON tjc28.pid = b.pid AND tjc28.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_06_1_sjc28 sjc28 ON sjc28.pid = b.pid AND sjc28.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_06_1_ptga ptga ON ptga.pid = b.pid AND ptga.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_06_1_esr esr ON esr.pid = b.pid AND esr.index_date = b.index_date
  LEFT JOIN a_ra_bio_inc_06_1_crp crp ON crp.pid = b.pid AND crp.index_date = b.index_date),
-- RA-BIO-INC-06 (inclusion): 申請前九十日至一百八十日間另有一次 DAS28 評估大於5.1（與最近一次評估間隔至少一個月）。
c_ra_bio_inc_06 AS (
  SELECT b.pid, b.index_date, (a_ra_bio_inc_06_1.val > 5.1) AS v,
         concat_ws(';', a_ra_bio_inc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_inc_06_1 ON a_ra_bio_inc_06_1.pid = b.pid AND a_ra_bio_inc_06_1.index_date = b.index_date),
a_ra_bio_exc_01_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_ACTIVE_TUBERCULOSIS' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-01 (exclusion): 一年內有活動性結核病。
c_ra_bio_exc_01 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_exc_01_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_exc_01_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_01_1 ON a_ra_bio_exc_01_1.pid = b.pid AND a_ra_bio_exc_01_1.index_date = b.index_date),
a_ra_bio_exc_02_1 AS (
  SELECT pid, index_date, (o.value_code IN ('LA6576-8')) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -365) AND b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_IGRA' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
a_ra_bio_exc_02_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TB_PREVENTIVE_THERAPY' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_TB_PREVENTIVE_THERAPY' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-02 (exclusion): 一年內丙型干擾素釋放試驗（IGRA）陽性而未接受潛伏結核預防性治療。
c_ra_bio_exc_02 AS (
  SELECT b.pid, b.index_date, (a_ra_bio_exc_02_1.v AND (NOT (coalesce(a_ra_bio_exc_02_2.n, 0) > 0))) AS v,
         concat_ws(';', a_ra_bio_exc_02_1.ev, a_ra_bio_exc_02_2.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_02_1 ON a_ra_bio_exc_02_1.pid = b.pid AND a_ra_bio_exc_02_1.index_date = b.index_date
  LEFT JOIN a_ra_bio_exc_02_2 ON a_ra_bio_exc_02_2.pid = b.pid AND a_ra_bio_exc_02_2.index_date = b.index_date),
a_ra_bio_exc_03_1 AS (
  SELECT pid, index_date, (o.value_code IN ('LA6576-8')) AS v,
         o.oid || '|' || strftime(o.effective, '%Y-%m-%d') AS ev
  FROM (SELECT *, row_number() OVER (PARTITION BY pid, index_date ORDER BY effective DESC, oid DESC) AS rn
        FROM (SELECT b.pid, b.index_date, o.oid, o.effective, o.value_num, o.value_code
  FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE <= b.index_date
  WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBSAG' AND vs.system = o.system AND vs.code = o.code))) o WHERE rn = 1),
a_ra_bio_exc_03_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, mid AS rid, authored AS d FROM medication x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBV_ANTIVIRAL_PROPHYLAXIS' AND vs.system = 'http://www.whocc.no/atc' AND vs.code = x.atc) OR EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBV_ANTIVIRAL_PROPHYLAXIS' AND vs.system = 'https://trialbox.local/fhir/CodeSystem/nhi-drug' AND vs.code = x.nhi_code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -180) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-03 (exclusion): B型肝炎表面抗原（HBsAg）陽性而半年內未併用抗病毒藥物預防。
c_ra_bio_exc_03 AS (
  SELECT b.pid, b.index_date, (a_ra_bio_exc_03_1.v AND (NOT (coalesce(a_ra_bio_exc_03_2.n, 0) > 0))) AS v,
         concat_ws(';', a_ra_bio_exc_03_1.ev, a_ra_bio_exc_03_2.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_03_1 ON a_ra_bio_exc_03_1.pid = b.pid AND a_ra_bio_exc_03_1.index_date = b.index_date
  LEFT JOIN a_ra_bio_exc_03_2 ON a_ra_bio_exc_03_2.pid = b.pid AND a_ra_bio_exc_03_2.index_date = b.index_date),
a_ra_bio_exc_04_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_MALIGNANCY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -1825) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-04 (exclusion): 五年內有惡性腫瘤病史。
c_ra_bio_exc_04 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_exc_04_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_exc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_04_1 ON a_ra_bio_exc_04_1.pid = b.pid AND a_ra_bio_exc_04_1.index_date = b.index_date),
a_ra_bio_exc_05_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_PREGNANCY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -280) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-05 (exclusion): 懷孕中（二百八十日內有懷孕診斷）。
c_ra_bio_exc_05 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_exc_05_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_exc_05_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_05_1 ON a_ra_bio_exc_05_1.pid = b.pid AND a_ra_bio_exc_05_1.index_date = b.index_date),
a_ra_bio_exc_06_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_SERIOUS_INFECTION' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -30) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-06 (exclusion): 三十日內有嚴重感染（敗血症、肺炎）。
c_ra_bio_exc_06 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_exc_06_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_exc_06_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_06_1 ON a_ra_bio_exc_06_1.pid = b.pid AND a_ra_bio_exc_06_1.index_date = b.index_date),
a_ra_bio_exc_07_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, cid AS rid, coalesce(onset, recorded) AS d FROM condition x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HEART_FAILURE' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d <= b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-EXC-07 (exclusion): 有心衰竭（NYHA 第三或第四級）病史。
c_ra_bio_exc_07 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_exc_07_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_exc_07_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_exc_07_1 ON a_ra_bio_exc_07_1.pid = b.pid AND a_ra_bio_exc_07_1.index_date = b.index_date),
a_ra_bio_ren_01_1_tjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'TJC28') WHERE rn = 1),
a_ra_bio_ren_01_1_sjc28 AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'SJC28') WHERE rn = 1),
a_ra_bio_ren_01_1_ptga AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'https://trialbox.local/fhir/CodeSystem/clinical-score' AND o.code = 'PTGA') WHERE rn = 1),
a_ra_bio_ren_01_1_esr AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '4537-7') WHERE rn = 1),
a_ra_bio_ren_01_1_crp AS (
  SELECT pid, index_date, value_num, oid, effective FROM (
    SELECT b.pid, b.index_date, o.value_num, o.oid, o.effective,
           row_number() OVER (PARTITION BY b.pid, b.index_date ORDER BY o.effective DESC, o.oid DESC) AS rn
    FROM base b JOIN observation o ON o.pid = b.pid AND o.effective::DATE BETWEEN (b.index_date + -90) AND b.index_date
    WHERE o.system = 'http://loinc.org' AND o.code = '1988-5') WHERE rn = 1),
a_ra_bio_ren_01_1 AS (
  SELECT b.pid, b.index_date, (CASE WHEN tjc28.value_num IS NULL OR sjc28.value_num IS NULL OR ptga.value_num IS NULL THEN NULL WHEN esr.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.7 * ln(esr.value_num) WHEN crp.value_num IS NOT NULL THEN 0.56 * sqrt(tjc28.value_num) + 0.28 * sqrt(sjc28.value_num) + 0.014 * ptga.value_num + 0.36 * ln(crp.value_num + 1) + 0.96 ELSE NULL END) AS val, concat_ws(';', tjc28.oid || '|' || strftime(tjc28.effective, '%Y-%m-%d'), sjc28.oid || '|' || strftime(sjc28.effective, '%Y-%m-%d'), ptga.oid || '|' || strftime(ptga.effective, '%Y-%m-%d'), esr.oid || '|' || strftime(esr.effective, '%Y-%m-%d'), crp.oid || '|' || strftime(crp.effective, '%Y-%m-%d')) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_ren_01_1_tjc28 tjc28 ON tjc28.pid = b.pid AND tjc28.index_date = b.index_date
  LEFT JOIN a_ra_bio_ren_01_1_sjc28 sjc28 ON sjc28.pid = b.pid AND sjc28.index_date = b.index_date
  LEFT JOIN a_ra_bio_ren_01_1_ptga ptga ON ptga.pid = b.pid AND ptga.index_date = b.index_date
  LEFT JOIN a_ra_bio_ren_01_1_esr esr ON esr.pid = b.pid AND esr.index_date = b.index_date
  LEFT JOIN a_ra_bio_ren_01_1_crp crp ON crp.pid = b.pid AND crp.index_date = b.index_date),
-- RA-BIO-REN-01 (renewal): 續用申請前九十日內須有完整之 DAS28 評估。
c_ra_bio_ren_01 AS (
  SELECT b.pid, b.index_date, (a_ra_bio_ren_01_1.val >= 0) AS v,
         concat_ws(';', a_ra_bio_ren_01_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_ren_01_1 ON a_ra_bio_ren_01_1.pid = b.pid AND a_ra_bio_ren_01_1.index_date = b.index_date),
a_ra_bio_doc_01_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, oid AS rid, effective::DATE AS d FROM observation x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_HBSAG' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-DOC-01 (documentation): 一年內B型肝炎表面抗原（HBsAg）檢驗報告。
c_ra_bio_doc_01 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_doc_01_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_doc_01_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_doc_01_1 ON a_ra_bio_doc_01_1.pid = b.pid AND a_ra_bio_doc_01_1.index_date = b.index_date),
a_ra_bio_doc_02_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, oid AS rid, effective::DATE AS d FROM observation x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_ANTI_HBC' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -365) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-DOC-02 (documentation): 一年內B型肝炎核心抗體（anti-HBc）檢驗報告。
c_ra_bio_doc_02 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_doc_02_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_doc_02_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_doc_02_1 ON a_ra_bio_doc_02_1.pid = b.pid AND a_ra_bio_doc_02_1.index_date = b.index_date),
a_ra_bio_doc_03_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, oid AS rid, effective::DATE AS d FROM observation x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_IGRA' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -180) AND b.index_date
  GROUP BY b.pid, b.index_date),
a_ra_bio_doc_03_2 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, rid, effective AS d FROM report x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_CHEST_X_RAY' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -180) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-DOC-03 (documentation): 六個月內結核篩檢：丙型干擾素釋放試驗（IGRA）或胸部X光報告。
c_ra_bio_doc_03 AS (
  SELECT b.pid, b.index_date, ((coalesce(a_ra_bio_doc_03_1.n, 0) > 0) OR (coalesce(a_ra_bio_doc_03_2.n, 0) > 0)) AS v,
         concat_ws(';', a_ra_bio_doc_03_1.ev, a_ra_bio_doc_03_2.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_doc_03_1 ON a_ra_bio_doc_03_1.pid = b.pid AND a_ra_bio_doc_03_1.index_date = b.index_date
  LEFT JOIN a_ra_bio_doc_03_2 ON a_ra_bio_doc_03_2.pid = b.pid AND a_ra_bio_doc_03_2.index_date = b.index_date),
a_ra_bio_doc_04_1 AS (
  SELECT b.pid, b.index_date, count(*) AS n,
         string_agg(e.rid || '|' || strftime(e.d, '%Y-%m-%d'), ';' ORDER BY e.d, e.rid) AS ev
  FROM base b JOIN (SELECT pid, oid AS rid, effective::DATE AS d FROM observation x WHERE EXISTS (SELECT 1 FROM vs WHERE vs.vs_id = 'VS_ESR_OR_CRP' AND vs.system = x.system AND vs.code = x.code)) e ON e.pid = b.pid AND e.d BETWEEN (b.index_date + -90) AND b.index_date
  GROUP BY b.pid, b.index_date),
-- RA-BIO-DOC-04 (documentation): 九十日內紅血球沉降速率（ESR）或C反應蛋白（CRP）檢驗報告。
c_ra_bio_doc_04 AS (
  SELECT b.pid, b.index_date, (coalesce(a_ra_bio_doc_04_1.n, 0) > 0) AS v,
         concat_ws(';', a_ra_bio_doc_04_1.ev) AS ev
  FROM base b
  LEFT JOIN a_ra_bio_doc_04_1 ON a_ra_bio_doc_04_1.pid = b.pid AND a_ra_bio_doc_04_1.index_date = b.index_date)
SELECT b.pid, b.index_date,
  c_ra_bio_inc_01.v AS "C_RA-BIO-INC-01", c_ra_bio_inc_01.ev AS "E_RA-BIO-INC-01",
  c_ra_bio_inc_02.v AS "C_RA-BIO-INC-02", c_ra_bio_inc_02.ev AS "E_RA-BIO-INC-02",
  c_ra_bio_inc_03.v AS "C_RA-BIO-INC-03", c_ra_bio_inc_03.ev AS "E_RA-BIO-INC-03",
  c_ra_bio_inc_04.v AS "C_RA-BIO-INC-04", c_ra_bio_inc_04.ev AS "E_RA-BIO-INC-04",
  c_ra_bio_inc_05.v AS "C_RA-BIO-INC-05", c_ra_bio_inc_05.ev AS "E_RA-BIO-INC-05",
  c_ra_bio_inc_06.v AS "C_RA-BIO-INC-06", c_ra_bio_inc_06.ev AS "E_RA-BIO-INC-06",
  c_ra_bio_exc_01.v AS "C_RA-BIO-EXC-01", c_ra_bio_exc_01.ev AS "E_RA-BIO-EXC-01",
  c_ra_bio_exc_02.v AS "C_RA-BIO-EXC-02", c_ra_bio_exc_02.ev AS "E_RA-BIO-EXC-02",
  c_ra_bio_exc_03.v AS "C_RA-BIO-EXC-03", c_ra_bio_exc_03.ev AS "E_RA-BIO-EXC-03",
  c_ra_bio_exc_04.v AS "C_RA-BIO-EXC-04", c_ra_bio_exc_04.ev AS "E_RA-BIO-EXC-04",
  c_ra_bio_exc_05.v AS "C_RA-BIO-EXC-05", c_ra_bio_exc_05.ev AS "E_RA-BIO-EXC-05",
  c_ra_bio_exc_06.v AS "C_RA-BIO-EXC-06", c_ra_bio_exc_06.ev AS "E_RA-BIO-EXC-06",
  c_ra_bio_exc_07.v AS "C_RA-BIO-EXC-07", c_ra_bio_exc_07.ev AS "E_RA-BIO-EXC-07",
  c_ra_bio_ren_01.v AS "C_RA-BIO-REN-01", c_ra_bio_ren_01.ev AS "E_RA-BIO-REN-01",
  c_ra_bio_doc_01.v AS "C_RA-BIO-DOC-01", c_ra_bio_doc_01.ev AS "E_RA-BIO-DOC-01",
  c_ra_bio_doc_02.v AS "C_RA-BIO-DOC-02", c_ra_bio_doc_02.ev AS "E_RA-BIO-DOC-02",
  c_ra_bio_doc_03.v AS "C_RA-BIO-DOC-03", c_ra_bio_doc_03.ev AS "E_RA-BIO-DOC-03",
  c_ra_bio_doc_04.v AS "C_RA-BIO-DOC-04", c_ra_bio_doc_04.ev AS "E_RA-BIO-DOC-04"
FROM base b
LEFT JOIN c_ra_bio_inc_01 ON c_ra_bio_inc_01.pid = b.pid AND c_ra_bio_inc_01.index_date = b.index_date
LEFT JOIN c_ra_bio_inc_02 ON c_ra_bio_inc_02.pid = b.pid AND c_ra_bio_inc_02.index_date = b.index_date
LEFT JOIN c_ra_bio_inc_03 ON c_ra_bio_inc_03.pid = b.pid AND c_ra_bio_inc_03.index_date = b.index_date
LEFT JOIN c_ra_bio_inc_04 ON c_ra_bio_inc_04.pid = b.pid AND c_ra_bio_inc_04.index_date = b.index_date
LEFT JOIN c_ra_bio_inc_05 ON c_ra_bio_inc_05.pid = b.pid AND c_ra_bio_inc_05.index_date = b.index_date
LEFT JOIN c_ra_bio_inc_06 ON c_ra_bio_inc_06.pid = b.pid AND c_ra_bio_inc_06.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_01 ON c_ra_bio_exc_01.pid = b.pid AND c_ra_bio_exc_01.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_02 ON c_ra_bio_exc_02.pid = b.pid AND c_ra_bio_exc_02.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_03 ON c_ra_bio_exc_03.pid = b.pid AND c_ra_bio_exc_03.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_04 ON c_ra_bio_exc_04.pid = b.pid AND c_ra_bio_exc_04.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_05 ON c_ra_bio_exc_05.pid = b.pid AND c_ra_bio_exc_05.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_06 ON c_ra_bio_exc_06.pid = b.pid AND c_ra_bio_exc_06.index_date = b.index_date
LEFT JOIN c_ra_bio_exc_07 ON c_ra_bio_exc_07.pid = b.pid AND c_ra_bio_exc_07.index_date = b.index_date
LEFT JOIN c_ra_bio_ren_01 ON c_ra_bio_ren_01.pid = b.pid AND c_ra_bio_ren_01.index_date = b.index_date
LEFT JOIN c_ra_bio_doc_01 ON c_ra_bio_doc_01.pid = b.pid AND c_ra_bio_doc_01.index_date = b.index_date
LEFT JOIN c_ra_bio_doc_02 ON c_ra_bio_doc_02.pid = b.pid AND c_ra_bio_doc_02.index_date = b.index_date
LEFT JOIN c_ra_bio_doc_03 ON c_ra_bio_doc_03.pid = b.pid AND c_ra_bio_doc_03.index_date = b.index_date
LEFT JOIN c_ra_bio_doc_04 ON c_ra_bio_doc_04.pid = b.pid AND c_ra_bio_doc_04.index_date = b.index_date
ORDER BY b.pid, b.index_date
